izpack/izpack

izpack-core/src/main/java/com/izforge/izpack/core/rules/logic/AndCondition.java
izpack-core/src/main/java/com/izforge/izpack/core/rules/logic/NotCondition.java
izpack-core/src/main/java/com/izforge/izpack/core/rules/logic/OrCondition.java
izpack-core/src/main/java/com/izforge/izpack/core/rules/logic/XorCondition.java
izpack-core/src/main/java/com/izforge/izpack/core/rules/process/RefCondition.java
izpack-core/src/test/java/com/izforge/izpack/core/rules/RulesEngineImplTest.java
izpack-core/src/test/resources/com/izforge/izpack/core/rules/poorly_defined_and_condition.xml
izpack-core/src/test/resources/com/izforge/izpack/core/rules/poorly_defined_not_condition.xml

Added more validation for conditions of type and, not, xor  and or.

Izpack 1202

---

izpack-core/src/main/java/com/izforge/izpack/core/data/DefaultVariables.java
izpack-core/src/test/java/com/izforge/izpack/core/data/DefaultVariablesTest.java

see https://jira.codehaus.org/browse/IZPACK-1216

Izpack 1216

---

izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java
izpack-core/src/main/java/com/izforge/izpack/core/variable/filters/CaseStyleFilter.java
izpack-core/src/test/java/com/izforge/izpack/core/variable/filters/CaseStyleFilterTest.java
izpack-dist/src/main/resources/schema/5.0/izpack-types-5.0.xsd
izpack-event/src/main/java/com/izforge/izpack/event/ConfigurationInstallerListener.java

IZPACK-1229: Implement a filter , which translates a value to all uppercase or all lowercase

IZPACK-1229: Implement a uppercase / lowercase filter

---

izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/spa.xml

Add the spanish translation for all the existing english keys at the moment.
All the file has been adapted and modified in order to sort the keys in the
same order than in the english "eng.xml" file
This pull request in about the jira issue IZPACK-1092 
http://jira.codehaus.org/browse/IZPACK-1092

[IZPACK-1092] Add the spanish translation (spa.xml) for all the existing english keys.

---

izpack-panel/src/main/java/com/izforge/izpack/panels/packs/PacksConsolePanel.java

PacksConsolePanel has been changed for printing the localized pack names instead the pack ids.
The method used is the same that in other classes like TreePacksConsolePanel from the library
The jira issue is: http://jira.codehaus.org/browse/IZPACK-1232

[IZPACK-1232] PacksConsolePanel prints now the localized pack name.

---

izpack-installer/src/main/java/com/izforge/izpack/installer/console/AbstractConsolePanel.java
izpack-installer/src/main/java/com/izforge/izpack/installer/console/ConsolePanelView.java
izpack-installer/src/main/java/com/izforge/izpack/installer/console/ConsolePanels.java

There is a weird error when having a DataValidator emitting a Status.WARNING instead of error, but just for console installations. The Swing installer behaves like expected. In the console installation, the user must exactly three times confirm OK to get to the next panel.
I injected generating a stacktrace to figure out what is repeating here:
```
Message broker connection
--> Row 1: URL: [tcp://localhost:7000] 
Enter the row number (1..1) to edit, 2 to continue, 3 to redisplay, 4 to add a row
2
Could not connect to broker URL: tcp://localhost:7000. Reason: java.net.ConnectException: Connection refused
Enter O for OK, C to Cancel: 
O
java.lang.Exception: O
at com.izforge.izpack.core.handler.ConsolePrompt.confirm(ConsolePrompt.java:162)
at …
```

IZPACK-1245 Console installer: panel DataValidator emitting a WARNING called three times before the panel switches

---

izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/ces.xml
izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/deu.xml
izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/eng.xml
izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/custom/CustomInputField.java

The "Add"/"Remove" button labels for custom input fields on a UserInputPanel should be translated.
Adding the basic translations I know (english, german, czech) and asking the community to add translations for more languages.

[IZPACK-1249] UserInputPanel - "custom" type input field - Swing button labels "Add"/"Remove" not translated

---

izpack-core/src/test/java/com/izforge/izpack/core/variable/filters/RegularExpressionFilterTest.java

This adds a basic unit test for the RegularExpressionFilter.

Added new JUnit test: RegularExpressionFilterTest

---

izpack-util/src/test/java/com/izforge/izpack/util/xmlmerge/XmlMergeTest.java

Fix for test failure if path contains a space on windows.

---

izpack-event/pom.xml
izpack-util/src/main/java/com/izforge/izpack/util/config/base/spi/AbstractParser.java
izpack-util/src/test/java/com/izforge/izpack/util/config/base/spi/AbstractParserTest.java

This is a fix for https://github.com/izpack/izpack/issues/361.
The problem is described in issue 361.

Fix for #361

---

izpack-event/src/main/java/com/izforge/izpack/event/AntAction.java

Provided the following definition in the resource AntActionSpec.xml:
```xml
<antcall order="beforepack" buildresource="service.xml" logfile="${ant.log.file}" logfile_append="true" condition="Install">
<property name="INSTALL_PATH" value="${INSTALL_PATH}" />
<target name="dispatch" />
</antcall>
```
If `${ant.log.file}` doesn't already exist, the first `<antaction ... logfile_append="true" />` logs to the standard output instead of that file.
Update: At the end this seems to happen also for `logfile_append="false"`, but if the parent directory of the logfile didn't exist (although it is automatically created recursively before the log file is created).

[IZPACK-1265] AntActionInstallerListener: Log file not created for <antaction logfile="..."> attribute if its parent directories do not exist

---

izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java

This PR solves [IZPACK-1266](https://izpack.atlassian.net/browse/IZPACK-1266):
The following install.xml:
```xml
...
<panels>
<panel classname="TargetPanel" id="panel.target"/>
<panel classname="UserInputPanel" id="panel.test" condition="izpack.selected.Example Core"/>
<panel classname="SummaryPanel"/>
<panel classname="FinishPanel"/>
</panels>
<packs>
<pack name="Example Core" required="yes" id="core.package">
<description>The core files required for $APP_NAME</description>
</pack>
</packs>
...
```
cannot be compiled, resulting in the following compiler stacktrace ({{mvn -X}}):
```
Failure during compilation process
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
at …
```

[IZPACK-1266] References to conditions izpack.selected.<packname> not validated during compiling

---

izpack-installer/src/main/java/com/izforge/izpack/installer/requirement/LockFileChecker.java

This PR fixes [IZPACK-1267](https://izpack.atlassian.net/browse/IZPACK-1267):
Overriding the single instance mode check of an installer according to
- https://izpack.atlassian.net/wiki/pages/editpage.action?pageId=491674: 
`-DMULTIINSTANCE=true` on the command line
- https://izpack.atlassian.net/wiki/pages/viewpage.action?pageId=491662:
`<singleinstance>` in the `<info>` section
is broken after some refactoring in 5.0 and should be reestablished.

[IZPACK-1267] Overriding single instance installer mode broken

---

izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java

see https://izpack.atlassian.net/browse/IZPACK-1278

IZPACK-1278: improve error message

---

izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/swe.xml
izpack-panel/src/main/java/com/izforge/izpack/panels/packs/PacksConsolePanel.java

Pull request that fixes IZPACK-1295
https://izpack.atlassian.net/browse/IZPACK-1295
Fixed problem that packs were installed in wrong order while using console mode.
This is a show-stopper for us so I would appreciate swift handling.
Cheers
Jonas

IZPACK-1295

---

izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/jpn.xml

Japanese langpack was corrupted because of wrong encoding.

Fixed corrupted strings

---

izpack-panel/src/main/java/com/izforge/izpack/panels/shortcut/ShortcutPanelLogic.java

Fix for https://izpack.atlassian.net/browse/IZPACK-1246.

[IZPACK-1246] PM WARNING: Cannot write to '/usr/share/applications' java.io.IOException: Permission denied when creating shortcuts under Linux

---

izpack-installer/src/main/java/com/izforge/izpack/installer/console/AbstractTextConsolePanel.java

The GUI panels support the variables substitution. 
The corresponding Text Console Panels like HTMLInfoConsolePanel, HTMLHelloConsolePanel which extend this class should also support the variables substitution.

Variables substitution in Text Console Panel

---

izpack-panel/src/main/java/com/izforge/izpack/panels/packs/PacksConsolePanel.java

This fix solves [IZPACK-1311](https://izpack.atlassian.net/browse/IZPACK-1311):
This issue is about some smaller errors in ``PacksConsolePanel``:
- If using ``PacksPanel`` in console installation mode and the user makes some changes to the initial defaults here, in case of choosing *Redisplay* the changes the user made before get lost. For this case the initial defaults are shown again. The *Redisplay* option should always preserve the user changes.
- When entering the ``PacksConsolePanel``, there is not used the standard translation for the ``PacksPanel`` GUI title.
- Hidden packs are shown, but should be suppressed like in GUI mode.

PacksConsolePanel - fix Redisplay, add panel title, don't show hidden packs

---

izpack-ant/src/main/java/com/izforge/izpack/ant/IzPackTask.java
izpack-ant/src/main/java/com/izforge/izpack/ant/IzpackAntRunnable.java
izpack-ant/src/main/java/com/izforge/izpack/ant/logging/AntHandler.java
izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java
izpack-compiler/src/main/java/com/izforge/izpack/compiler/helper/AssertionHelper.java
izpack-compiler/src/main/java/com/izforge/izpack/compiler/listener/CmdlinePackagerListener.java
izpack-compiler/src/main/java/com/izforge/izpack/compiler/logging/MavenStyleLogFormatter.java
izpack-compiler/src/test/java/com/izforge/izpack/compiler/CompilerConfigMockedTest.java
izpack-compiler/src/test/java/com/izforge/izpack/compiler/bootstrap/CompilerLauncherTest.java
izpack-compiler/src/test/java/com/izforge/izpack/compiler/container/TestCompilerContainer.java
izpack-maven-plugin/src/main/java/org/izpack/mojo/IzPackNewMojo.java
izpack-maven-plugin/src/main/java/org/izpack/mojo/logging/MavenStyleLogFormatter.java
izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/field/FieldReader.java
izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/field/SimpleChoiceReader.java
izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/field/UserInputPanelSpec.java
izpack-test/src/test/java/com/izforge/izpack/compiler/container/TestCompilationContainer.java
izpack-test/src/test/java/com/izforge/izpack/integration/AbstractInstallationTest.java
izpack-util/src/main/java/com/izforge/izpack/util/LogFormatter.java
izpack-util/src/main/java/com/izforge/izpack/util/LogHandler.java

This request implements two compiler issues:
- [IZPACK-1315](https://izpack.atlassian.net/browse/IZPACK-1315) - Panel conditions in userInputSpec.xml not checked during compiling, installer fails later
- [IZPACK-1317](https://izpack.atlassian.net/browse/IZPACK-1315) - Improve logging formatting for Maven / Ant

Combined fix IZPACK-1315 + IZPACK-1317

---

izpack-panel/src/test/java/com/izforge/izpack/panels/target/TargetPanelHelperTest.java
izpack-util/src/main/java/com/izforge/izpack/util/file/FileUtils.java

IZPACK-1330: Fix for test errors under windows with JDK8

IZPACK-1330: Fix for test errors under windows with JDK8

---

izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java

IZPACK-1305: Fixed destination for natives.

IZPACK-1305: Fixed destination for natives.

---

izpack-test/src/test/java/com/izforge/izpack/integration/windows/WindowsConsoleInstallationTest.java

IZPACK-1331: Fixed integration tests under windows.

---

izpack-panel/src/main/java/com/izforge/izpack/panels/finish/FinishPanel.java

IZPACK-1333: FinishPanel must use the uninstaller path from installData

IZPACK-1333: FinishPanel must use the uninstaller path from installData

---

izpack-panel/src/main/java/com/izforge/izpack/panels/target/TargetConsolePanel.java
izpack-panel/src/test/java/com/izforge/izpack/panels/target/TargetConsolePanelTest.java

Usage of izpack.api.prompt instead of console.prompt

Change for IZPACK-1319

---

izpack-installer/src/main/java/com/izforge/izpack/installer/bootstrap/Installer.java
izpack-installer/src/main/java/com/izforge/izpack/installer/bootstrap/InstallerConsole.java
izpack-installer/src/main/java/com/izforge/izpack/installer/bootstrap/InstallerGui.java
izpack-installer/src/main/java/com/izforge/izpack/installer/container/impl/ConsoleInstallerContainer.java
izpack-installer/src/main/java/com/izforge/izpack/installer/language/LanguageConsoleDialog.java
izpack-installer/src/main/java/com/izforge/izpack/installer/language/LanguageDialog.java
izpack-installer/src/main/java/com/izforge/izpack/installer/language/Languages.java

- console implementation of language selection
- fixed parameter "-language" that was not accepted from command line
for both gui and console

Fix for IZPACK-1313

---

izpack-util/src/main/java/com/izforge/izpack/util/Console.java

Fixed newline handling in console messagebox depending on terminal settings.

IZPACK-1342: Console installer regressions (post-fix)

---

izpack-core/src/main/java/com/izforge/izpack/core/rules/RulesEngineImpl.java
izpack-tools/src/main/java/com/izforge/izpack/util/OsVersionConstants.java
izpack-tools/src/main/java/com/izforge/izpack/util/Platforms.java

@rkrell I'll provide the unit tests later or tomorrow.

IZPACK-1348: Added Windows 10 to platforms. Must provide tests later.

---

izpack-test/src/test/java/com/izforge/izpack/integration/windows/WindowsConsoleInstallationTest.java

Tests now pass on my system with administrator rights.

IZPACK-1331: Fix tests under Windows with admin privileges

---

izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/field/file/AbstractFileFieldReader.java

- small stuff probably only a typo which resulted in getting wrong attribute to description field

Fix wrong description field for file input field

---

izpack-event/src/main/java/com/izforge/izpack/event/RegistryInstallerListener.java
izpack-uninstaller/src/main/java/com/izforge/izpack/uninstaller/gui/UninstallerFrame.java

Create the Uninstaller directory before the Uninstaller icon is copied.
Add i18n for UninstallerFrame title.

Fix for IZPACK-1350 and IZPACK-1025

---

izpack-api/src/main/java/com/izforge/izpack/api/data/Info.java
izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java
izpack-compiler/src/main/resources/schema/5.0/izpack-installation-5.0.xsd
izpack-panel/src/main/java/com/izforge/izpack/panels/target/TargetConsolePanel.java
izpack-panel/src/main/java/com/izforge/izpack/panels/target/TargetPanel.java
izpack-panel/src/main/java/com/izforge/izpack/panels/target/TargetPanelAutomation.java
izpack-panel/src/main/java/com/izforge/izpack/panels/target/TargetPanelHelper.java
izpack-panel/src/test/java/com/izforge/izpack/panels/target/TargetPanelHelperTest.java

Added additional attribute readinstallationinformation that defines
whether to read .installationinformation file and thus check packs
compatibility

IZPACK-1368

---

izpack-ant/src/main/java/com/izforge/izpack/ant/IzPackTask.java
izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java
izpack-compiler/src/main/java/com/izforge/izpack/compiler/helper/TargetFileSet.java
izpack-compiler/src/main/java/com/izforge/izpack/compiler/listener/CompilerListener.java
izpack-compiler/src/main/java/com/izforge/izpack/compiler/listener/SimpleCompilerListener.java
izpack-compiler/src/main/java/com/izforge/izpack/compiler/merge/PanelMerge.java
izpack-compiler/src/main/java/com/izforge/izpack/compiler/util/CompilerClassLoader.java
izpack-core/src/main/java/com/coi/tools/os/win/AccessControlEntry.java
izpack-core/src/main/java/com/coi/tools/os/win/AccessControlList.java
izpack-core/src/main/java/com/izforge/izpack/core/container/AbstractContainer.java
izpack-installer/src/main/java/com/izforge/izpack/installer/container/provider/GUIInstallDataProvider.java
izpack-installer/src/main/java/com/izforge/izpack/installer/language/LanguageConsoleDialog.java
izpack-maven-plugin/src/it/sample/src/izpack/src/myCompany/tools/install/listener/ChmodCompilerListener.java
izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/field/FieldValidator.java
izpack-test/src/test/java/com/izforge/izpack/integration/UninstallHelper.java
izpack-util/src/main/java/com/izforge/izpack/data/PackInfo.java

parameterized several Classes, Types, Maps and Iterators to avoid warnings
see https://izpack.atlassian.net/browse/IZPACK-1358

Izpack 1358

---

izpack-core/src/main/java/com/izforge/izpack/core/rules/process/CompareVersionsCondition.java
izpack-core/src/main/java/com/izforge/izpack/core/rules/process/CompareVersionsMajorCondition.java
izpack-installer/src/main/java/com/izforge/izpack/installer/container/impl/GUIInstallerContainer.java

remove unused imports
see https://izpack.atlassian.net/browse/IZPACK-1359

Izpack 1359

---

izpack-panel/src/main/java/com/izforge/izpack/panels/licence/LicencePanel.java

Added missing key listener to yes/no buttons.

IZPACK-1273

---

izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java
izpack-util/src/main/java/com/izforge/izpack/util/file/FileUtils.java

New pull request which works on JDK 1.6.

Use temporary directory to avoid deleting existing directories.

---

izpack-panel/src/main/java/com/izforge/izpack/panels/packs/PacksModel.java

IZPACK-1372

---

izpack-compiler/src/main/resources/schema/5.0/izpack-installation-5.0.xsd

see https://izpack.atlassian.net/browse/IZPACK-1174

IZPACK-1174: add missing attribute "jar" to <panel>

---

izpack-maven-plugin/pom.xml
izpack-maven-plugin/src/main/java/org/izpack/mojo/IzPackNewMojo.java
izpack-maven-plugin/src/test/java/org/izpack/mojo/IzPackNewMojoTest.java
izpack-maven-plugin/src/test/resources/pom-izpack-1400.xml
pom.xml

see https://izpack.atlassian.net/browse/IZPACK-1400

IZPACK-1400  Maven Build: installer does not recognize external overwritten property

---

izpack-core/src/main/java/com/izforge/izpack/core/rules/process/ContainsCondition.java

for the following code:
```
<conditions>
<condition id="pattern_found" type="contains">
<value byLine="true" regex="true">my.*pattern</value>
<file>test.txt</file>
</condition>
</conditions>
```
**Please pull after #511 only!**

IZPACK-1411: ContainsCondition - Avoid NPE

---

izpack-compiler/src/main/resources/schema/5.0/izpack-types-5.0.xsd
izpack-core/src/main/java/com/izforge/izpack/core/rules/process/ContainsCondition.java

because after applying [IZPACK-1408](https://izpack.atlassian.net/browse/IZPACK-1408) it is not useful anymore. See [IZPACK-1409](https://izpack.atlassian.net/browse/IZPACK-1409) for further details.

IZPACK-1409: Remove attribute byLine from <value>  in contains-<condition>

---

izpack-compiler/src/main/java/com/izforge/izpack/compiler/Compiler.java
izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java

Step 1 - checks at compilation time, split addInfo into 2 separate
methods because javaVersion is checked too late

IZPACK-1415

---

izpack-api/src/main/java/com/izforge/izpack/api/data/PackFile.java
izpack-installer/src/main/java/com/izforge/izpack/installer/unpacker/LooseFileUnpacker.java

IZPACK-1417

---

izpack-installer/src/main/java/com/izforge/izpack/installer/unpacker/LooseFileUnpacker.java

Just a suggested solution in form of PR.

IZPACK-1419

---

izpack-panel/src/main/java/com/izforge/izpack/panels/treepacks/CheckBoxNodeRenderer.java

Fixed the loop on TreePacks panel.

IZPACK-1416

---

izpack-panel/src/main/java/com/izforge/izpack/panels/packs/PacksPanelAutomationHelper.java

Fixed logger for automated packs panel when pack is required but conditions are not met.

IZPACK-1420

---

izpack-panel/src/main/java/com/izforge/izpack/panels/packs/PacksConsolePanel.java

[IZPACK-1427](https://izpack.atlassian.net/browse/IZPACK-1427):
Modified the logic of packs selection for console packs panel.

IZPACK-1427

---

izpack-installer/src/main/java/com/izforge/izpack/installer/language/LanguageConsoleDialog.java

[IZPACK-1430](https://izpack.atlassian.net/browse/IZPACK-1430):
Throw nice exception and handle shutdown.

IZPACK-1430

---

izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/console/password/ConsolePasswordGroupField.java

Empty password field does not return null immediately

IZPACK-1447

---

izpack-panel/src/main/java/com/izforge/izpack/panels/installationgroup/InstallationGroupConsolePanel.java
izpack-panel/src/main/java/com/izforge/izpack/panels/installationgroup/InstallationGroupPanel.java
izpack-panel/src/main/java/com/izforge/izpack/panels/installationgroup/InstallationGroupPanelAutomationHelper.java

Fixed InstallGroupPanel console

IZPACK-1393

---

izpack-gui/src/main/java/com/izforge/izpack/gui/GUIPrompt.java

Added style formatting to JOptionPane messages that would sometimes be
too long to handle.

IZPACK-1429

---

izpack-installer/src/main/java/com/izforge/izpack/installer/requirement/JavaVersionChecker.java
izpack-installer/src/test/java/com/izforge/izpack/installer/requirement/JavaVersionCheckerTest.java

Java version checker changes - "strict" checks update version as well if applicable during runtime

IZPACK-1451

---

izpack-core/src/main/java/com/izforge/izpack/core/resource/ResourceManager.java

Just some cleanup in the code, no impact.

Code cleanup in ResourceManager

---

izpack-installer/src/main/java/com/izforge/izpack/installer/container/impl/GUIInstallerContainer.java
izpack-installer/src/main/java/com/izforge/izpack/installer/gui/InstallerFrame.java
izpack-panel/src/test/java/com/izforge/izpack/panels/pdflicence/PDFLicencePanelTest.java
izpack-panel/src/test/java/com/izforge/izpack/panels/test/AbstractPanelTest.java

Fix for [IZPACK-1484](https://izpack.atlassian.net/browse/IZPACK-1484)

IZPACK-1484: Moved set frame title to InstallerFrame to be set after the language was selected

---

izpack-installer/src/main/java/com/izforge/izpack/installer/event/InstallerListeners.java

This PR implements [IZPACK-1489](https://izpack.atlassian.net/browse/IZPACK-1489):
In IzPack, there can be used exceptions of type IzPackException in custom installer listeners which can be set to warning level. Currently, if there is registered a set of installer listeners, and during execution of these listeners there is thrown an IzPackException of type warning, a message box is opened with the question whether to continue the installation, but before that the execution of all subsequent installer listeners is implicitly skipped.
As far as I can see this currently doesn't affect built-in listener types, but it can be very useful for own listener implementations to inform the user but execute all other actions also of different listeners after the occurrence of a non-critical event.
The …

IZPACK-1489: Allow execution of subsequent installer listeners if a warning is thrown during the execution of an InstallerListener

---

izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/bra.xml

This PR provides the change for [IZPACK-1491](https://izpack.atlassian.net/browse/IZPACK-1491).

IZPACK-1491: Translation package bra for console installation

---

izpack-event/src/main/java/com/izforge/izpack/event/RegistryInstallerListener.java
izpack-util/src/main/java/com/izforge/izpack/util/SelfModifier.java
izpack-util/src/main/java/com/izforge/izpack/util/file/DirectoryScanner.java
izpack-util/src/main/java/com/izforge/izpack/util/file/FileUtils.java

- use commons-io where applicable
- remove unused code
- fixed some javadoc issues
No issue has been assigned. These are changes that have been found by the way, no functional change nor breaking of valid APIs.

Code optimization and cleanup

---

izpack-compiler/src/main/resources/schema/5.0/izpack-processing-5.0.xsd
izpack-panel/src/main/java/com/izforge/izpack/panels/process/ErrorHandlingStrategy.java
izpack-panel/src/main/java/com/izforge/izpack/panels/process/ProcessPanelWorker.java

This is fix for proposed improvement https://izpack.atlassian.net/browse/IZPACK-1485

Izpack 1485 make continuation on failure configurable

---

izpack-installer/src/main/java/com/izforge/izpack/util/LogUtils.java

https://izpack.atlassian.net/browse/IZPACK-1513

Fixed NPE if logconfig is not available.

---

izpack-installer/pom.xml
izpack-installer/src/test/java/com/izforge/izpack/installer/requirement/JavaVersionCheckerTest.java

IzPack-1514 - JUnit test fails if build on Java with non-numeric version parts

---

izpack-event/src/main/java/com/izforge/izpack/event/RegistryInstallerListener.java

Fix NPE if <uninstaller write="false" /> is configured.

IZPACK-1519: Fix NPE if <uninstaller write="false" /> is configured.

---

izpack-event/src/main/java/com/izforge/izpack/event/RegistryInstallerListener.java

This is just a small post-cleanup. Nothing to worry about :-)

IZPACK-1519: Just a small cleanup - no functional change

---

izpack-api/src/main/java/com/izforge/izpack/api/event/AbstractInstallerListener.java
izpack-api/src/main/java/com/izforge/izpack/api/event/AbstractUninstallerListener.java
izpack-api/src/main/java/com/izforge/izpack/api/event/InstallerListener.java
izpack-api/src/main/java/com/izforge/izpack/api/event/UninstallerListener.java
izpack-api/src/test/java/com/izforge/izpack/api/event/UninstallerListenerTest.java
izpack-event/src/main/java/com/izforge/izpack/event/AntActionUninstallerListener.java
izpack-event/src/main/java/com/izforge/izpack/event/BSFUninstallerListener.java
izpack-event/src/main/java/com/izforge/izpack/event/RegistryUninstallerListener.java
izpack-event/src/test/java/com/izforge/izpack/event/BSFUninstallerListenerTest.java
izpack-installer/src/main/java/com/izforge/izpack/installer/event/InstallerListeners.java
izpack-installer/src/main/java/com/izforge/izpack/installer/unpacker/UnpackerBase.java
izpack-test-listener/src/main/java/com/izforge/izpack/test/listener/TestUninstallerListener.java
izpack-uninstaller/src/main/java/com/izforge/izpack/uninstaller/event/UninstallerListeners.java

Implementation of [IZPACK-1528](https://izpack.atlassian.net/browse/IZPACK-1528)

IZPACK-1528: Add progress listener to UninstallerListener#beforeDelete/InstallerListener#beforePacks

---

izpack-installer/src/test/java/com/izforge/izpack/installer/container/TestLanguageContainer.java

Implementation of [IZPACK-1530](https://izpack.atlassian.net/browse/IZPACK-1530)

IZPACK-1530: Fix NPE in LanguageDialogTest

---

izpack-gui/src/main/java/com/izforge/izpack/gui/GUIPrompt.java

Implementation of [IZPACK-1532](https://izpack.atlassian.net/browse/IZPACK-1532)
This pull request also adds a name of "OptionPane.label" to the message label. This fixes a number of GUI tests which require that name to find the label in assertions.

IZPACK-1532: Run GUIPrompt#showMessageDialog in EDT

---

izpack-installer/src/test/java/com/izforge/izpack/test/provider/GUIInstallDataMockProvider.java

Implementation of [IZPACK-1531](https://izpack.atlassian.net/browse/IZPACK-1531)

IZPACK-1531: Fix NPE in GUIPrompt#showMessageDialog when invoked from tests

---

izpack-panel/src/test/java/com/izforge/izpack/panels/userinput/UserInputPanelTest.java
izpack-panel/src/test/resources/com/izforge/izpack/panels/userinput/check/userInputSpec.xml

Implementation of [IZPACK-1534](https://izpack.atlassian.net/browse/IZPACK-1534)

IZPACK-1534: Fix tests in UserInputPanelTest#testCheck

---

izpack-panel/src/test/java/com/izforge/izpack/panels/userinput/UserInputPanelTest.java
izpack-panel/src/test/resources/com/izforge/izpack/panels/userinput/rule/userInputSpec.xml

Implementation of [IZPACK-1537](https://izpack.atlassian.net/browse/IZPACK-1537)

IZPACK-1537: Fix UserInputPanelTest#testRuleField

---

izpack-panel/src/test/java/com/izforge/izpack/panels/userinput/UserInputPanelTest.java
izpack-panel/src/test/resources/com/izforge/izpack/panels/userinput/text/userInputSpec.xml

Implementation of [IZPACK-1538](https://izpack.atlassian.net/browse/IZPACK-1538)

IZPACK-1538: Fix UserInputPanelTest#testTextField

---

izpack-panel/src/test/java/com/izforge/izpack/panels/userinput/UserInputPanelTest.java
izpack-panel/src/test/resources/com/izforge/izpack/panels/userinput/refresh/userInputSpec.xml

Implementation of [IZPACK-1539](https://izpack.atlassian.net/browse/IZPACK-1539)

IZPACK-1539: Fix UserInputPanelTest#testRefreshDynamicVariables

---

izpack-installer/src/main/java/com/izforge/izpack/util/LogUtils.java

[IZPACK-1542](https://izpack.atlassian.net/browse/IZPACK-1542)

IZPACK-1542: Fix NPE if '<logging level="OFF" />' is configured

---

izpack-panel/src/main/java/com/izforge/izpack/panels/path/PathInputPanel.java
izpack-panel/src/test/java/com/izforge/izpack/panels/target/TargetPanelTest.java

Implementation of [IZPACK-1544](https://izpack.atlassian.net/browse/IZPACK-1544)

IZPACK 1544: Fix tests in TargetPanel

---

izpack-panel/src/test/java/com/izforge/izpack/panels/pdflicence/PDFLicencePanelTest.java

Implementation of [IZPACK-1545](https://izpack.atlassian.net/browse/IZPACK-1545)

IZPACK-1545: Extend AbstractPanelTest in PDFLicencePanelTest and add some real test cases

---

pom.xml

Implementation of [IZPACK-1547](https://izpack.atlassian.net/browse/IZPACK-1547)

IZPACK-1547: Update icepdf viewer to version 6.2.2

---

izpack-panel/src/test/java/com/izforge/izpack/panels/PanelDisplayTest.java
izpack-panel/src/test/java/com/izforge/izpack/panels/defaulttarget/DefaultTargetPanelTest.java
izpack-panel/src/test/java/com/izforge/izpack/panels/process/ProcessPanelTest.java
izpack-panel/src/test/java/com/izforge/izpack/panels/target/TargetPanelTest.java
izpack-panel/src/test/java/com/izforge/izpack/panels/test/AbstractPanelTest.java
izpack-panel/src/test/java/com/izforge/izpack/panels/userinput/UserInputPanelTest.java

Implementation of Implementation of  [IZPACK-1549](https://izpack.atlassian.net/browse/IZPACK-1549)

IZPACK 1549: Replace Thread.sleep with condition and fix timing issues

---

.travis.yml
izpack-panel/src/test/java/com/izforge/izpack/panels/pdflicence/PDFLicencePanelTest.java

Implementation of  [IZPACK-1550](https://izpack.atlassian.net/browse/IZPACK-1550)

IZPACK 1550: Integration of GUI tests into CI build

---

izpack-core/src/main/java/com/izforge/izpack/core/handler/ConsolePrompt.java
izpack-installer/src/main/java/com/izforge/izpack/installer/console/ConsolePanelView.java
izpack-installer/src/test/java/com/izforge/izpack/installer/requirement/AbstractRequirementCheckerTest.java
izpack-installer/src/test/java/com/izforge/izpack/installer/requirement/JDKCheckerTest.java
izpack-panel/src/test/java/com/izforge/izpack/panels/userinput/console/AbstractConsoleFieldTest.java
izpack-panel/src/test/java/com/izforge/izpack/panels/userinput/console/check/ConsoleCheckFieldTest.java
izpack-test-common/src/main/java/com/izforge/izpack/test/util/TestConsole.java
izpack-uninstaller/src/main/java/com/izforge/izpack/uninstaller/console/ConsoleUninstallerContainer.java
izpack-util/src/main/java/com/izforge/izpack/util/Console.java

Fixed messages being initialized too early in some cases for computer locale rather than selected locale.

IZPACK-1541

---

pom.xml

[IZPACK-1526](https://izpack.atlassian.net/browse/IZPACK-1526):
This fixes the test errors but the termination of the JVM should be detected, but I don't know the reason why the JVM is terminated.

IZPACK-1526: Fix test errors (but the termination of the JVM should be detected!)

---

izpack-panel/src/main/java/com/izforge/izpack/panels/checkedhello/CheckedHelloPanelAutomationHelper.java
izpack-panel/src/main/java/com/izforge/izpack/panels/htmlhello/HTMLHelloPanelAutomationHelper.java
izpack-panel/src/main/java/com/izforge/izpack/panels/htmlinfo/HTMLInfoPanelAutomationHelper.java
izpack-panel/src/main/java/com/izforge/izpack/panels/htmllicence/HTMLLicencePanelAutomationHelper.java
izpack-panel/src/main/java/com/izforge/izpack/panels/info/InfoPanelAutomationHelper.java
izpack-panel/src/main/java/com/izforge/izpack/panels/licence/LicencePanelAutomationHelper.java
izpack-panel/src/main/java/com/izforge/izpack/panels/pdflicence/PDFLicencePanelAutomationHelper.java
izpack-panel/src/main/java/com/izforge/izpack/panels/simplefinish/SimpleFinishPanelAutomationHelper.java
izpack-panel/src/main/java/com/izforge/izpack/panels/summary/SummaryPanelAutomationHelper.java

Added automation helpers for default panels that had at least some console implementation.

IZPACK-1486

---

izpack-test-common/src/main/java/com/izforge/izpack/test/junit/PicoRunner.java

Implementation of  [IZPACK-1555](https://izpack.atlassian.net/browse/IZPACK-1555)

IZPACK-1555: Create test container outside of the EDT in PicoRunner#createTest

---

.travis.yml
izpack-test-common/src/main/java/com/izforge/izpack/test/junit/PicoRunner.java
izpack-test/src/test/resources/samples/silverpeas/postprocess.xml
pom.xml

Implementation of  [IZPACK-1556](https://izpack.atlassian.net/browse/IZPACK-1556)
This pull request depends on IZPACK-1555.

Izpack 1556: Fix InstallationTest

---

izpack-panel/src/test/java/com/izforge/izpack/panels/pdflicence/PDFLicencePanelTest.java
pom.xml

Implementation of  [IZPACK-1558](https://izpack.atlassian.net/browse/IZPACK-1558)

IZPACK-1558: Add support for running integration tests w/o unit tests

---

izpack-compiler/src/main/java/com/izforge/izpack/compiler/packager/impl/Packager.java
izpack-compiler/src/test/java/com/izforge/izpack/compiler/packager/impl/PackagerTest.java

Implementation of  [IZPACK-1561](https://izpack.atlassian.net/browse/IZPACK-1561)

IZPACK-1561: Use buffered output stream in Packager#writePacks

---

izpack-compiler/src/main/resources/schema/5.0/izpack-processing-5.0.xsd
izpack-panel/src/main/java/com/izforge/izpack/panels/process/ErrorHandlingStrategy.java
izpack-panel/src/main/java/com/izforge/izpack/panels/process/ProcessPanelWorker.java

Adds an option to ignore processpanel executefile tasks failures.
https://izpack.atlassian.net/browse/IZPACK-1013

IZPACK-1013: ProcessPanel - add job switch to ignore failures

---

izpack-test/src/test/java/com/izforge/izpack/integration/HelperTestMethod.java
izpack-test/src/test/java/com/izforge/izpack/integration/InstallationTest.java

Implementation of  [IZPACK-1567](https://izpack.atlassian.net/browse/IZPACK-1567)

IZPACK-1567: Execute calls to LanguageDialog#initLangPack within the EDT in InstallerTest

---

izpack-compiler/src/main/resources/schema/5.0/izpack-userinput-5.0.xsd
izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/field/Field.java
izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/field/FieldConfig.java
izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/field/FieldProcessor.java
izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/field/FieldReader.java
izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/field/rule/RuleField.java
izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/processor/PortProcessor.java
izpack-panel/src/test/java/com/izforge/izpack/panels/userinput/UserInputPanelTest.java
izpack-panel/src/test/java/com/izforge/izpack/panels/userinput/field/TestFieldConfig.java
izpack-panel/src/test/java/com/izforge/izpack/panels/userinput/field/TestFieldProcessor.java
izpack-panel/src/test/resources/com/izforge/izpack/panels/userinput/processors/userInputSpec.xml

[IZPACK-1568](https://izpack.atlassian.net/browse/IZPACK-1568)

IZPACK-1568: Allow several field processors and store the result in separate variables

---

izpack-tools/src/main/java/com/izforge/izpack/util/Platform.java

Allow UNC path in syntax validator.

IZPACK-1572

---

izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/GUIField.java

Add tooltips to rule input fields as well.

IZPACK-1573

---

src/lib/com/izforge/izpack/panels/LicencePanel.java

https://stackoverflow.com/questions/14403881/izpack-how-to-show-utf-8-license-with-licensepanel

IZPACK-1575: LicensePanel Encoding Issue

---

izpack-gui/src/main/java/com/izforge/izpack/gui/GUIPrompt.java

Create a button instance of its own for Close.

IZPACK-1574

---

.travis.install-maven.sh
.travis.yml
izpack-util/src/test/java/com/izforge/izpack/util/PrivilegedRunnerTest.java

@rkrell I stumbled over some travis issues when running with my #658 pull request. This will fix the build and enhances the _PrivilegedRunnerTest_ to include also the JVM arguments, that may be differ on the travis build environment

Travis udpate

---

izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/field/SimpleChoiceReader.java

IZPACK-1592 replace variables in combo box labels

---

izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/console/ConsoleChoiceField.java
izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/console/ConsoleField.java

Display choice field label when available in console.

IZPACK-1606

---

izpack-installer/src/main/java/com/izforge/izpack/installer/unpacker/GUIPackResources.java

This pull request finally fixes IZPACK-1469. It also works correctly with online and offline installation.

Fixing IZPACK-1469

---

izpack-panel/src/main/java/com/izforge/izpack/panels/packs/PacksModel.java
izpack-panel/src/main/java/com/izforge/izpack/panels/treepacks/TreePacksConsolePanel.java

If not negative number appear as pack size or total size in TreePackPanel

FIX capacity overflow when pack size exceeds int size

---

izpack-dist/pom.xml
izpack-maven-plugin/src/main/java/org/izpack/mojo/IzPackNewMojo.java

Fixed attaching of final artifact.

IZPACK-1596

---

izpack-installer/src/main/java/com/izforge/izpack/util/os/Unix_Shortcut.java

When installing using sudo in Linux, in order to install to, e.g., `/opt` directory, the shortcuts are created such that they are owned by root. I seems to me that this behaviour is invalid.

Fixes Unix shortcut ownership and permissions when installing using sudo

---

izpack-util/src/main/java/com/izforge/izpack/util/xmlmerge/matcher/AbstractAttributeMatcher.java

Return true when no other attribute comparison returns false.

IZPACK-1583

---

izpack-installer/src/main/java/com/izforge/izpack/installer/unpacker/ScriptParser.java
izpack-installer/src/test/java/com/izforge/izpack/installer/unpacker/ScriptParserTest.java

Fixes [IZPACK-1617](https://izpack.atlassian.net/browse/IZPACK-1617)

Fix issues with character encoding in parsable files

---

.travis.install-maven-archived.sh
.travis.yml

Fix broken jdk6 build on travis.

Fix broken jdk6 build on travis.

---

izpack-ant/src/main/java/com/izforge/izpack/ant/IzpackAntRunnable.java
izpack-ant/src/test/java/com/izforge/izpack/ant/IzPackTaskTest.java

[https://izpack.atlassian.net/browse/IZPACK-1638](https://izpack.atlassian.net/browse/IZPACK-1638)
I used an existing test class to demonstrate the problem.
Unfortunately the test is set to @Ignore for some reason...

support non string properties

---

.travis.settings.xml
.travis.yml
izpack-installer/src/main/java/com/izforge/izpack/installer/gui/InstallerFrame.java

IZPACK-1654: Fix broken travis build

IZPACK-1654: Fix broken travis build

---

.travis.settings.xml
.travis.yml

IZPACK-1654 Use OpenJDK for version 8 and all HTTPS

---

izpack-installer/src/main/java/com/izforge/izpack/installer/data/UninstallDataWriter.java
izpack-test/src/test/java/com/izforge/izpack/integration/UninstallDataWriterTest.java

IZPACK-1662 Fix by removing premature cast to Serializable

---

izpack-api/src/main/java/com/izforge/izpack/api/config/Registry.java
izpack-api/src/main/java/com/izforge/izpack/api/config/spi/AbstractParser.java
izpack-api/src/main/java/com/izforge/izpack/api/config/spi/IniParser.java
izpack-api/src/main/java/com/izforge/izpack/api/config/spi/OptionsParser.java
izpack-api/src/main/java/com/izforge/izpack/api/config/spi/RegBuilder.java
izpack-api/src/main/java/com/izforge/izpack/api/config/spi/RegEscapeTool.java
izpack-util/src/test/java/com/izforge/izpack/api/config/spi/AbstractParserTest.java
izpack-util/src/test/java/com/izforge/izpack/api/config/spi/IniParserTest.java

Fixed build failure on Win10 because of new registry entry types.

IZPACK-1668: Fixed build failure on Win10 because of new registry entry types.

---

izpack-maven-plugin/src/main/java/org/izpack/mojo/IzPackNewMojo.java

IZPACK-1655 - added option to exclude password properties.

IZPACK-1655 - Allow exclude of properties that may contain passwords

---

README.md

Changed README.md to move to travis-ci.com

Moved to travis-ci.com

---

izpack-panel/src/main/java/com/izforge/izpack/panels/shortcut/ShortcutPanelLogic.java

Implements program group fallback

IZPACK-1672 adds fall back to suggested program group name

---

pom.xml

Update maven plugins to current versions

IZPACK-1687: Update maven plugins to current versions

---

izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/eng.xml
izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/ita.xml
izpack-panel/src/main/java/com/izforge/izpack/panels/sudo/SudoPanel.java
izpack-test-common/src/main/java/com/izforge/izpack/test/util/ClassUtils.java
izpack-wrapper/src/main/java/utils/wrappers/izpack2run/Merge2In1.java
izpack-wrapper/src/main/resources/utils/wrappers/izpack2app/izpack2app.py
izpack-wrapper/src/main/resources/utils/wrappers/izpack2run/ant_usage_example.txt
izpack-wrapper/src/main/resources/utils/wrappers/izpack2run/linux_stub

This PR contains the changes from PR #704 and requested changes.

IZPACK-1688: Update PR #704

---

ide-config/jetbrains/CodeStyle.xml

This project doesn't use the most common coding style for java, so this file will help IntelliJ users to respect the coding styling.

IntelliJ CodeStyle

---

izpack-event/src/main/java/com/izforge/izpack/event/RegistryInstallerListener.java
izpack-panel/src/main/java/com/izforge/izpack/panels/packs/PacksModel.java

Correct calculated size to KB. Add support to set the "Publisher" in the registry. This can be done by adding a variable "Publisher".

IZPACK-1694: Correct calculated size to KB.

---

izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java

Fixes https://izpack.atlassian.net/browse/IZPACK-1680

[IZPACK-1680] Decode included jar's path when converting it to File

---

izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/pol.xml

This is based on PR https://github.com/izpack/izpack/pull/687, the old PR https://github.com/izpack/izpack/pull/687 is to be closed.

[IZPACK-1714] Missing Polish translations

---

izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/UserInputPanelAutomationHelper.java
izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/field/UserInputPanelSpec.java

Signed-off-by: Patrick Reinhart <patrick@reini.net>

[IZPACK-1725] Enables defaults during automated installation

---

.github/workflows/maven.yml

Signed-off-by: Patrick Reinhart <patrick@reini.net>

Updates github actions

---

izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/UserInputPanelAutomationHelper.java

Signed-off-by: Patrick Reinhart <patrick@reini.net>

[IZPACK-1726] Use default for unset variables only

---

izpack-panel/src/main/java/com/izforge/izpack/panels/userpath/UserPathConsolePanel.java
izpack-panel/src/main/java/com/izforge/izpack/panels/userpath/UserPathInputPanel.java
izpack-panel/src/main/java/com/izforge/izpack/panels/userpath/UserPathPanel.java
izpack-panel/src/main/java/com/izforge/izpack/panels/userpath/UserPathPanelAutomationHelper.java

[IZPACK-1731] UserPathPanel.intro message string does not work for UserPathPanel, no need for extendedIntro key
[IZPACK-1734] Missing properties implemenatation for UserPathPanel
[IZPACK-1731]: https://izpack.atlassian.net/browse/IZPACK-1731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IZPACK-1734]: https://izpack.atlassian.net/browse/IZPACK-1734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IZPACK-1731 & IZPACK-1734

---

izpack-util/pom.xml
pom.xml

Update to ant-1.10.13

---

izpack-panel/src/main/java/com/izforge/izpack/panels/path/PathInputConsolePanel.java
izpack-panel/src/main/java/com/izforge/izpack/panels/path/PathInputPanel.java

[IZPACK-1738] always show overwrite files dialog on new installation

---

izpack-api/src/main/java/com/izforge/izpack/api/data/PackFile.java
izpack-api/src/main/java/com/izforge/izpack/api/data/XPackFile.java
izpack-compiler/pom.xml
izpack-compiler/src/main/java/com/izforge/izpack/compiler/packager/impl/MultiVolumePackager.java
izpack-compiler/src/main/java/com/izforge/izpack/compiler/packager/impl/Packager.java
izpack-compiler/src/main/java/com/izforge/izpack/compiler/packager/impl/PackagerBase.java
izpack-installer/src/main/java/com/izforge/izpack/installer/unpacker/CompressedFileUnpacker.java
izpack-installer/src/main/java/com/izforge/izpack/installer/unpacker/UnpackerBase.java
izpack-util/pom.xml
izpack-util/src/main/java/com/izforge/izpack/util/StreamSupport.java

Adds compressed size and stream offset to back reference PackFile instance.

[IZPACK-1752] Fixes "Unexpected end of ZLIB input stream"

---

izpack-dist/pom.xml
izpack-maven-plugin/src/main/java/org/izpack/mojo/IzPackNewMojo.java
izpack-maven-plugin/src/test/java/org/izpack/mojo/IzPackNewMojoTest.java

You may like to refer to comments of PR https://github.com/izpack/izpack/pull/800

[IZPACK-1660] Maven IzPack Plugin - Incorrect Artifact Handling

---

izpack-compiler/src/main/resources/schema/5.0/izpack-registry-5.0.xsd

I added the missing entities reported in IZPACK-1760.

IZPACK-1760 Addition of missing entities

---

izpack-panel/src/main/java/com/izforge/izpack/panels/shortcut/ShortcutPanelAutomationHelper.java

In order to get the correct shortcut settings reload the shortcut data as first action.

[IZPACK-1775] Invoke refreshShortcutData() first

---

izpack-ant/src/main/java/com/izforge/izpack/ant/IzPackTask.java
izpack-ant/src/main/java/com/izforge/izpack/ant/IzpackAntRunnable.java

- Execute task using single thread executor and rethrow execution errors if any
- Fixes deprecation warnings for Hashtable
- Extracted constant for multiple used constant String

IZPACK-1779 Fix ANT task to fail on error

---

pom.xml

- switch from bcprov-jdk15on to bcprov-jdk18on
- switch from bcprov-ext-jdk15on to bcprov-ext-jdk18on

Bump org.bouncycastle libraries from 1.70 to 1.78.1

---

izpack-compiler/src/main/java/com/izforge/izpack/compiler/cli/CliAnalyzer.java
izpack-compiler/src/main/java/com/izforge/izpack/compiler/data/CompilerData.java
izpack-compiler/src/main/resources/version.properties
izpack-installer/src/main/java/com/izforge/izpack/installer/bootstrap/Installer.java
izpack-uninstaller/src/main/java/com/izforge/izpack/uninstaller/Uninstaller.java

Adds simple version output to installer, uninstaller & compiler.

[IZPACK-1784] Adds build to compiler info

---

.github/workflows/maven.yml

Moved display to ENV, save fluxbox log
