izpack-util/src/main/java/com/izforge/izpack/util/config/SingleConfigurableTask.java, izpack-util/src/main/java/com/izforge/izpack/util/config/base/BasicProfile.java, izpack-util/src/main/java/com/izforge/izpack/util/config/base/Profile.java
This is an initial solution to the JDK 8 buildability issue. Renaming this method avoids collision with the method found in documentation here:
http://docs.oracle.com/javase/8/docs/api/java/util/Map.html#remove-java.lang.Object-java.lang.Object-
=> IZPACK-1210: IzPack cannot build with JDK 8

izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java
Explicit check for null here since the lookup will return null if lafName doesn't exist, which causes NPE in the switch(feels) statment.
This also fixes 1190 and 1189 simultaneously, since both metal and aqua LAFs don't exist in the LookAndFeels class, so they're just a more specific case of 1190.
=> Fix for IZPACK-1191 (1190 and 1189 also)

izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/UserInputPanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/field/Field.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/GUIField.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/statictext/GUIStaticText.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/title/GUITitleField.java
This is a fix for issue https://jira.codehaus.org/browse/IZPACK-1211:
*UserInputPanel: Missing variable resolution in attribute <field><spec text="..."/><field> including the according translations*
Provided there is a panel specification in userInputSpec.xml like this:
```xml
<panel id="panel.test">
<field type="title" txt="Test panel" id="text.test.title" />
<field type="staticText" align="left" txt="${INSTALL_PATH}${FILE_SEPARATOR}${application.folder}" />
<field type="text" variable="targetsettings.target">
<spec txt="Target directory: ${INSTALL_PATH}${FILE_SEPARATOR}" id="text.targetsettings.target" size="20" set="${application.folder}" />
<validator class="com.izforge.izpack.panels.userinput.validator.NotEmptyValidator" txt="Target directory path is mandatory!" …
```
=> [IZPACK-1211] UserInputPanel: Missing variable resolution in attribute <field><spec text="..."/><field> including the according translations

izpack-api/src/main/java/com/izforge/izpack/api/data/Variables.java, izpack-core/src/main/java/com/izforge/izpack/core/data/DefaultVariables.java, izpack-installer/src/main/java/com/izforge/izpack/installer/console/AbstractConsolePanel.java, izpack-installer/src/main/java/com/izforge/izpack/installer/console/ConsolePanels.java, izpack-installer/src/main/java/com/izforge/izpack/installer/gui/IzPanelView.java, izpack-installer/src/main/java/com/izforge/izpack/installer/panel/AbstractPanelView.java, izpack-installer/src/main/java/com/izforge/izpack/installer/panel/AbstractPanels.java, izpack-installer/src/main/java/com/izforge/izpack/installer/panel/PanelView.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/UserInputConsolePanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/UserInputPanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/UserInputPanelAutomationHelper.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/field/Field.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/field/UserInputPanelSpec.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/combo/GUIComboField.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/file/GUIMultipleFileField.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/password/GUIPasswordGroupField.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/radio/GUIRadioField.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/rule/GUIRuleField.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/rule/RuleTextField.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/text/GUITextField.java
Supposed there is the following installer defined:
**userInputSpec.xml:**
```xml
<izpack:userinput version="5.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:izpack="http://izpack.org/schema/userinput" xsi:schemaLocation="http://izpack.org/schema/userinput http://izpack.org/schema/5.0/izpack-userinput-5.0.xsd">
<panel id="panel.test">
<field type="title" txt="Test panel" id="text.test.title" />
<field type="radio" variable="dbsystem">
<spec txt="with set">
<choice txt="MSSQL" value="mssql" id="text.dbsystem.mssql" />
<choice txt="Oracle" value="oracle" id="text.dbsystem.oracle" set="true" />
<choice txt="SAP Hana" value="hdb" id="text.dbsystem.hana" />
</spec>
</field>
<field type="divider"/>
<field type="radio" variable="dbsystem2">
<spec txt="with default">
<choice …
```
=> [IZPACK-1212] UserInputPanel: Radio defaults apply just for the first radio field on one and the same panel

izpack-core/src/main/java/com/izforge/izpack/core/data/DefaultVariables.java, izpack-core/src/main/java/com/izforge/izpack/core/data/DynamicVariableImpl.java, izpack-core/src/test/java/com/izforge/izpack/core/data/DefaultVariablesTest.java
With this fix the dynamic variables, which depend on other ones, are computated correct on the first refresh() already. The Issue is olved with this pull request.
=> Izpack 1182: Evaluation of dynamic variables, which depends on other ones

izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/UserInputPanel.java
Just a post-fix for http://jira.codehaus.org/browse/IZPACK-1199: "Don't refresh a dynamic variable if it has been set by the user on a UserInputPanel - another post-fix for that issue (avoid "null" as blocked variable name)"
Avoid "null" variable names.
=> [IZPACK-1199] - post-fix

izpack-api/src/main/java/com/izforge/izpack/api/data/Variables.java, izpack-core/src/main/java/com/izforge/izpack/core/data/DefaultVariables.java, izpack-core/src/test/java/com/izforge/izpack/core/data/DefaultVariablesTest.java
This fix does end the loop which is generated by a definition like
{code:xml}
<dynamicvariables>
<variable name="a" value="${b}" />
<variable name="b" value="${a}" />
</dynamicvariables>
{code}
=> Izpack 1215: Terminate loop

izpack-core/src/main/java/com/izforge/izpack/core/variable/ConfigFileValue.java, izpack-core/src/test/java/com/izforge/izpack/core/data/DynamicVariableImplTest.java, izpack-core/src/test/java/com/izforge/izpack/core/rules/RulesEngineImplTest.java, izpack-core/src/test/resources/com/izforge/izpack/core/data/wrapper.conf, izpack-util/src/main/java/com/izforge/izpack/util/config/base/Ini.java, izpack-util/src/main/java/com/izforge/izpack/util/config/base/Options.java
Assuming the following configuration file wrapper.conf:
```
wrapper.java.command=C:\Program Files\Java\jdk1.7.0_51\bin\java
```
and the following dynamic variable definition:
```xml
<variable name="java.cmd" type="options" escape="false" ignorefailure="true" file="${INSTALL_PATH}/bin/wrapper.conf" key="wrapper.java.command">
<filters>
<regex regexp="[/\\]+" replace="/" global="true" />
</filters>
</variable>
```
After refreshing. the variable {{java.cmd}} should have been evaluated to `C:/Program Files/Java/jdk1.7.0_51/bin/java`.
Actually It contains `C:Program FilesJavajdk1.7.0_51/bin/java`.
This happens just for reading values from files, plain values with backslashes and `escape="false"` work as expected.
There is also a small cleanup for some other unit tests.
=> [IZPACK-1218] - Dynamic variables: escape="false" ignored for reading values from configuration files

izpack-core/src/main/java/com/izforge/izpack/core/rules/RulesEngineImpl.java, izpack-core/src/main/java/com/izforge/izpack/core/rules/logic/AndCondition.java, izpack-core/src/main/java/com/izforge/izpack/core/rules/logic/NotCondition.java, izpack-core/src/main/java/com/izforge/izpack/core/rules/logic/OrCondition.java, izpack-core/src/main/java/com/izforge/izpack/core/rules/logic/XorCondition.java, izpack-core/src/test/java/com/izforge/izpack/core/rules/RulesEngineImplTest.java, izpack-core/src/test/resources/com/izforge/izpack/core/rules/conditions.xml
I have to tweak the original solution from pull request #301 a bit.
Actually there is also a possibility to have nested logical conditions, like this:
```xml
<condition type="exists" id="Update">
<file>${INSTALL_PATH}/some_path</file>
</condition>
<condition type="not" id="Install">
<condition type="ref" refid="Update" />
</condition>
<condition type="and" id="linuxInstallOrUpdate">
<condition type="ref" refid="izpack.linuxinstall" />
<condition type="or" id="installOrUpdate">
<condition type="ref" refid="Install" />
<condition type="ref" refid="Update" />
</condition>
</condition>
```
which isn't covered neither in unit tests not in the documentation.
=> Tweak for [IZPACK-1202] NPE in AndCondition due to a bad condition definition

izpack-dist/src/main/resources/schema/5.0/izpack-installation-5.0.xsd
The current installation schema does not allow the "installGroups' attribute, which is required for the InstallationGroupPanel.
This fix will add the optional attribute so that an IzPack 5 configuration file that uses the InstallationGroupPanel can be successfully validated.
=> Enable InstallationGroupPanel logic in installation schema

izpack-api/src/main/java/com/izforge/izpack/api/data/Info.java, izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java, izpack-installer/src/main/java/com/izforge/izpack/installer/container/impl/InstallerContainer.java, izpack-installer/src/main/java/com/izforge/izpack/installer/requirement/ExpiredChecker.java, izpack-installer/src/main/java/com/izforge/izpack/installer/requirement/RequirementsChecker.java, izpack-installer/src/test/java/com/izforge/izpack/installer/requirement/AbstractRequirementCheckerTest.java, izpack-installer/src/test/java/com/izforge/izpack/installer/requirement/ExpiredCheckerTest.java, izpack-installer/src/test/java/com/izforge/izpack/installer/requirement/RequirementsCheckerTest.java
This checker lets installers automatically expire on a date specified by variable "InstallerExpiresDate" in the installer XML file.  The date must be in the format "yyyy-MM-dd".  If "InstallerExpiresDate" is not defined, the installer does not expire.
=> Expired checker

.classpath, src/dtd/installation.dtd
eclipse needs BSF classes for compilation, it is not included in the current eclipse project setup.
Added the hidden attribute to the pack definition so that a hidden pack does not cause validation errors.
=> [4.3] eclipse settings fix and DTD fix

izpack-util/src/main/java/com/izforge/izpack/util/config/SingleConfigurableTask.java
Deleting key/value-entries from a properties-file does go the wrong way. See [IZPACK-1226](http://jira.codehaus.org/browse/IZPACK-1226).
=> IZPACK-1226: ConfigurationInstallerListener does not remove entries as configured

izpack-installer/src/main/java/com/izforge/izpack/installer/unpacker/UnpackerBase.java
While debugging with the -DDEBUG flag on, the log told me "FINE: Found 0 executable files" even though I have one configured.
Further investigation showed the debug log message referenced the wrong collection.
=> Fixed a misleading debug message.

izpack-util/src/main/java/com/izforge/izpack/util/config/SingleOptionFileTask.java
Just a quick fix for this inconvenience:
```
Feb 27, 2015 6:39:22 PM SEVERE: java.lang.NullPointerException
com.izforge.izpack.api.exception.InstallerException: java.lang.NullPointerException
at com.izforge.izpack.event.ConfigurationInstallerListener.performAllActions(ConfigurationInstallerListener.java:357)
at com.izforge.izpack.event.ConfigurationInstallerListener.afterPack(ConfigurationInstallerListener.java:261)
at com.izforge.izpack.installer.event.InstallerListeners.afterPack(InstallerListeners.java:287)
at com.izforge.izpack.installer.unpacker.UnpackerBase.unpack(UnpackerBase.java:412)
at com.izforge.izpack.installer.unpacker.UnpackerBase.unpack(UnpackerBase.java:251)
at com.izforge.izpack.installer.unpacker.UnpackerBase.run(UnpackerBase.java:233)
at …
```
=> Avoid NullPointerException in ConfigurationInstallerListener, if patchFile hasn't been defined in the descriptor

src/dtd/installation.dtd
According to Pack.java, validators are already supported. The DTD does not reflect that fact. This is simple fix of the installation DTD.
=> [4.3] Added validator element to pack element in DTD

izpack-api/src/main/java/com/izforge/izpack/api/exception/IzPackException.java, izpack-api/src/main/java/com/izforge/izpack/api/handler/AbstractPrompt.java, izpack-api/src/main/java/com/izforge/izpack/api/handler/Prompt.java, izpack-core/src/main/java/com/izforge/izpack/core/handler/ConsolePrompt.java, izpack-event/src/main/java/com/izforge/izpack/event/ActionBase.java, izpack-event/src/main/java/com/izforge/izpack/event/AntAction.java, izpack-event/src/main/java/com/izforge/izpack/event/AntActionInstallerListener.java, izpack-event/src/main/java/com/izforge/izpack/event/AntActionUninstallerListener.java, izpack-event/src/main/java/com/izforge/izpack/event/AntSeverity.java, izpack-gui/src/main/java/com/izforge/izpack/gui/GUIPrompt.java, izpack-installer/src/main/java/com/izforge/izpack/installer/event/InstallerListeners.java, izpack-installer/src/main/java/com/izforge/izpack/installer/unpacker/UnpackerBase.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/DelegatingPrompt.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/LoggingPrompt.java, izpack-panel/src/test/java/com/izforge/izpack/panels/process/ProcessConsolePanelTest.java, pom.xml
This pull request implements https://jira.codehaus.org/browse/IZPACK-1231:
If there occur Ant build failures in AntActionInstallerListener they are handled poorly at the moment. In each case, the installation fails with a messagebox containing the complete error trace not very useful for people just using an installer.
The error handling should be enhanced to the following possibilities:
- Hide the Ant stacktrace from the user or open it optionally
- Ant build stacktraces can be still seen in the AntAction log file.
- Introduce info, warning and error level
Also increased Ant dependency to version 1.9.4.
The enhanced API of messageboxes is can be used also in other custom listeners or elsewhere.
Stack traces and the severity can be packed into an IzPackException.
The documentation is also …
=> IZPACK-1231 - AntActionsInstallerListener: Improve error handling and messageboxes

izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/eng.xml, izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/spa.xml, izpack-panel/src/main/java/com/izforge/izpack/panels/target/TargetConsolePanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/console/ConsoleChoiceField.java, izpack-panel/src/test/java/com/izforge/izpack/panels/userinput/console/combo/ConsoleComboFieldTest.java
Add the localization support for some text hardcoded in the code (console classes).
1.
class "TargetConsolePanel" 
method "public boolean run(InstallData installData, Console console)"
text: "Select target path ["
2. 
class "ConsoleChoiceField"
method "public boolean More ...display()"
text: "input selection: "
The test has been changed too in order to load the messages.
This pull request in about the jira issue IZPACK-1222
http://jira.codehaus.org/browse/IZPACK-1222
This pull request depends on the previous pull request (for avoiding conflicts in spa.xml and eng.xml)
https://github.com/izpack/izpack/pull/331 
for the jira issue: http://jira.codehaus.org/browse/IZPACK-1092
=> [IZPACK-1222] Some text is hardcoded in english in console classes

izpack-gui/src/main/java/com/izforge/izpack/gui/GUIPrompt.java
Post-fix for IZPACK-1231: Remove showing stacktraces on the command line before opening error messageboxes, for instance on validation failures
=> Post-fix for IZPACK-1231: Remove showing stacktraces on the command line

izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/UserInputPanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/Component.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/GUIField.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/button/GUIButtonField.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/check/GUICheckField.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/combo/GUIComboField.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/custom/GUICustomField.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/divider/GUIDivider.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/file/AbstractGUIFileField.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/file/GUIMultipleFileField.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/password/GUIPasswordGroupField.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/radio/GUIRadioField.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/rule/GUIRuleField.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/search/GUISearchField.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/space/GUISpacer.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/statictext/GUIStaticText.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/text/GUITextField.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/title/GUITitleField.java
This pull request solves https://jira.codehaus.org/browse/IZPACK-1238:
On opening a user input panel during a Swing-based installation, there is not automatically focused the first valid input field. Instead, the user must navigate or click on it to do any input.
=> [IZPACK-1238] UserInputPanel: input fields not focused automatically onpanel activation

izpack-gui/src/main/java/com/izforge/izpack/gui/GUIPrompt.java, izpack-installer/src/main/java/com/izforge/izpack/installer/container/provider/GUIInstallDataProvider.java
This PR fixes https://jira.codehaus.org/browse/IZPACK-1240:
On Unix, when validating user inputs, in case of validation errors or warnings the installer opens a messagebox with a focused 'Close' button, but pressing ENTER doesn't close it, just ESC, SPACE or clicking it directly close these messageboxes.
This is specific to the Look and Feel. Activate/override the "Button.defaultButtonFollowsFocus" setting in general for all L&F.
=> [IZPACK-1240] Message boxes after validation failures cannot be closed using ENTER, but just by ESC, SPACE or clicking on the Close button

izpack-core/src/main/java/com/izforge/izpack/core/data/DefaultVariables.java
This is a post-fix regarding https://jira.codehaus.org/browse/IZPACK-1182:
Where possible, force resolving of dynamic variables independently of the order they are defined in.
=> Post-fix for [IZPACK-1182] Evaluation of dynamic variables, which depends on another one, fails

izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/file/AbstractGUIFileField.java
File/dir input fields still didn't receive the initial focus correctly.
This small change fixes this problem for them.
=> [IZPACK-1238] UserInputPanel: input fields not focused automatically on panel activation - post-fix

izpack-maven-plugin/src/main/resources/META-INF/plexus/components.xml
This affects https://jira.codehaus.org/browse/IZPACK-1241:
Mostly a short time after fresh IzPack snapshot deployments I've noticed build failures when using the special packaging type {{izpack-jar}} in the POM.
There are appearing errors like this:
```
10:04:58 [ERROR] Failed to execute goal org.codehaus.izpack:izpack-maven-plugin:5.0.0-rc5-SNAPSHOT:izpack (default-izpack) on project my-app: Execution default-izpack of goal org.codehaus.izpack:izpack-maven-plugin:5.0.0-rc5-SNAPSHOT:izpack failed: A required class was missing while executing org.codehaus.izpack:izpack-maven-plugin:5.0.0-rc5-SNAPSHOT:izpack: com/izforge/izpack/api/data/Info
10:04:58 [ERROR] -----------------------------------------------------
10:04:58 [ERROR] realm = …
```
=> [IZPACK-1241] Builds using custom packaging type izpack-jar sometimes fail after fresh IzPack snapshot deployments

izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java, izpack-core/src/main/java/com/izforge/izpack/core/data/DefaultVariables.java, izpack-core/src/main/java/com/izforge/izpack/core/data/DynamicVariableImpl.java, izpack-core/src/main/java/com/izforge/izpack/core/variable/ValueImpl.java, izpack-core/src/main/java/com/izforge/izpack/core/variable/filters/CaseStyleFilter.java, izpack-core/src/main/java/com/izforge/izpack/core/variable/filters/LocationFilter.java, izpack-core/src/main/java/com/izforge/izpack/core/variable/filters/RegularExpressionFilter.java
Fix for https://jira.codehaus.org/browse/IZPACK-1242:
Provided a definition like this:
```xml
<variable name="db.name" value="${db.url}" checkonce="true" condition="NotInstall+haveDatabaseURL+useMssql">
<filters>
<regex regexp="jdbc:jtds:sqlserver://[^:]+:\d+.*;DatabaseName=([^;]*)" select="\1" />
</filters>
</variable>
<variable name="db.name" value="${db.url}" checkonce="true" condition="NotInstall+haveDatabaseURL+useMssql">
<filters>
<regex regexp="jdbc:jtds:sqlserver://[^:]+:\d+/([^:;]+)" select="\1" />
</filters>
</variable>
```
currently the first of the above two definitions withing <dynamicvariables> is ignored. A warning comes up during compiling:
*Variable definition 'db.name' will be overwritten.*
The currently rule for uniqueness of a dynamic variable is bound to comparing …
=> [IZPACK-1242] Dynamic variable definitions with the same name and conditionid overwritten, although applying different filters for each of them

src/dtd/event/registry.dtd
According to code, the RegistrySpec.xml supports condition evaluation at
"pack", "key" and "value". This fix allows schema validation.
=> Updated registry.dtd

izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java, izpack-core/src/main/java/com/izforge/izpack/core/rules/RulesEngineImpl.java
This is a post-fix for https://jira.codehaus.org/browse/IZPACK-1109:
The error reoccured for some usecase.
This should be additionally prevented at compile time. It should not be allowed to use undefined conditions. This PR aborts the compilation on any unresolved condition reference in any element that might have a 'condition' attribute.
=> [IZPACK-1109] Panel conditions throw NPE when some condition does not exist in AND statement - post-fix

src/dtd/event/registry.dtd
registry.dtd was missing an attribute for a VALUE where IzPack decides
wether to store an already existing registry entry or not.
This is a standalone commit and has no connection to any open issue.
=> Added the saveprevious attribute

izpack-core/src/main/java/com/izforge/izpack/core/handler/ConsolePrompt.java
Currently, the title for warning and error messages is not shown in console installations. This makes ot hard for the user know what's going on.
There should be a more user-firendly console interface as equivalent to error and warning messageboxes in Swing installers.
Example of the current behavior:
There is just shown the warning message of a panel validator:
```
Could not connect to broker URL: tcp://localhost:7000. Reason: java.net.ConnectException: Connection refused
Enter O for OK, C to Cancel: 
```
Example of the desired behavior:
There should eb also shown the title and some horizontal lines as separators to recognize a messagebox equivalent:
```
------------------------------------------------------------------------------------------------------------
Validation failed - …
```
=> [IZPACK-1247] Console installer - no title displayed for warning/error messages in comparison to GUI installer

izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/console/ConsoleField.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/console/custom/ConsoleCustomField.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/custom/CustomInputField.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/custom/CustomInputRows.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/custom/GUICustomField.java
For console as well as GUI installers there is a few complaints about the layout of the new "custom" type input field:
- GUI: the button labels of "add"/"remove" should be "Add"/"Remove".
- GUI: The insets of the "Add"/"Remove" buttons against the input rows should be increased.
- Console: There is no user-friendly recognition which are the rows available for inputs, rather add row numbers or some indentations.
- Console: It should be possible to directly edit specific rows without redisplaying and navigating all valid rows before.
TODO: There is still to be solved the translations of the user tests of the custom field for both installer types.
=> [IZPACK-1248] UserInputPanel - "custom" input field layout improvements for console/GUI installers

izpack-core/src/main/java/com/izforge/izpack/merge/jar/JarMerge.java
Related to https://jira.codehaus.org/browse/IZPACK-1250:
There is problem with uninstaller.jar content when we use installer jar with "(1)" for example `install (1).jar` it very often case when we download installer several times.
In this case `JarMerge` performs `replaceAll` with "(1)" that treated as regular expression.
=> Fixed problem with uninstaller.jar merge content

izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/UserInputPanel.java
This is a postfix for the above issue:
The first field of an UserInputPanel panel has been focused twice (the focus jumped back unexpectedly)
=> [IZPACK-1238] UserInputPanel: input fields not focused automatically on panel activation - post fix

izpack-installer/src/main/java/com/izforge/izpack/installer/gui/InstallerFrame.java, izpack-installer/src/main/java/com/izforge/izpack/installer/gui/InstallerView.java, izpack-panel/src/main/java/com/izforge/izpack/panels/install/InstallPanel.java
Hitting Enter once more after activating the InstallPanel pushes the Quit button, which isn't most probably desirable for any use case - disable Quit while installation is in progress to avoid inconsistent final states.
=> Fix for installation can be aborted without a warning by mistake during processing the InstallPanel by hitting Enter once more

izpack-util/src/main/java/com/izforge/izpack/util/config/SingleConfigurableTask.java, izpack-util/src/main/java/com/izforge/izpack/util/config/base/spi/OptionsBuilder.java, izpack-util/src/test/java/com/izforge/izpack/util/config/SingleConfigurableTaskTest.java, izpack-util/src/test/java/com/izforge/izpack/util/config/SingleOptionTestTask.java
This fix solves several issues with properties auto-numbering and patching them described in [IZPACK-1257](https://izpack.atlassian.net/browse/IZPACK-1257):
Patching auto-numbered properties ending on .0, .1 etc. using ConfigurationInstallerListeners is broken, The installer reads such keys in its special mannerf but does never use them for patching although this is intended.
For an example, consider the following situation:
cluster.properties coming with a new installer:
```
failover.connection.0=10.1.1.1:8000
failover.connection.1=10.1.1.2:8000
```
cluster.properties.configbak previously installed and automatically renamed by the installer before overwriting:
```
failover.connection.0=192.168.1.1:8000
failover.connection.1=192.168.1.2:8000
failover.connection.2=192.168.1.3:8000
``` …
=> [IZPACK-1257] ConfigurationInstallerListener: Preserving auto-numbered options broken

izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/UserInputConsolePanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/UserInputPanel.java
Recently there has been introduced the feature of freezing dynamic variables as soon as a panel is reached where there can be set in a user input to not override user inputs.
This should be valid just for variables really shown on the panel, not for those hidden by a condition.
This fixes [IZPACK-1255](https://izpack.atlassian.net/browse/IZPACK-1255).
=> [IZPACK-1255] UserInputPanel: Continue refreshing panel variables which are not shown depending upon a condition

izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/Component.java
This request solves [IZPACK-1254](https://izpack.atlassian.net/browse/IZPACK-1254):
There's a regression that breaks the feature introduced with some earlier 5.0 RC5 snapshot:
Read-only fields according to https://izpack.atlassian.net/wiki/display/IZPACK/Displaying+panels+and+fields+read-only not displayed read-only in Swing installer, although there values are not processed.
=> [IZPACK-1254] UserInputPanel: readonly/displayHidden fields not displayed read-only

izpack-installer/src/main/java/com/izforge/izpack/installer/unpacker/UnpackerBase.java, izpack-util/src/main/java/com/izforge/izpack/util/config/SingleConfigurableTask.java, izpack-util/src/test/java/com/izforge/izpack/util/config/SingleConfigurableTaskTest.java
- Fixed regression of [IZPACK-1257](https://izpack.atlassian.net/browse/IZPACK-1257) - ConfigurationInstallerListener: Preserving auto-numbered options broken:
Index > 0 in auto-numbered options led to IndexOutOfBoundException - allow indexes > 0, added also a new unit test for this situation.
- Fixed regression in implementation of [IZPACK-1253](https://izpack.atlassian.net/browse/IZPACK-1253) - ClassCastException in Unpacker if non-IzPackException is given as root cause to InstallerException from listener:
ClassCastExceptions on InstallerException with root cause exception different than IzPackException.
=> Fix last-minute regressions for IzPack 5.0.0

izpack-util/src/main/java/com/izforge/izpack/util/config/SingleConfigurableTask.java
This change fixes [IZPACK-1263](https://izpack.atlassian.net/browse/IZPACK-1263):
Provided the following constellation:
Resource ConfigurationActionsSpec.xml:
```xml
<configurableset type="options" cleanup="true"
keepOldKeys="false" keepOldValues="true" overwrite="true"
todir="${INSTALL_PATH}/config"
condition="Update">
<fileset dir="${INSTALL_PATH}/config">
<include name="http.properties.configbak"/>
</fileset>
<mapper type="glob" from="*.properties.configbak" to="*.properties"/>
</configurableset>
```
Preinstalled and renamed ${INSTALL_PATH}/config/http.properties.configbak:
```
http.servlet.jnlp.param.resources.jar.1=lib/server
http.servlet.jnlp.param.resources.jar.2=lib/shared
http.servlet.jnlp.param.resources.jar.3=lib/client
```
New ${INSTALL_PATH}/config/http.properties:
``` …
```
=> [IZPACK-1263] ConfigurationInstallerListener: configurableset ignores autonumbered properties beginning on index > 0

izpack-util/src/main/java/com/izforge/izpack/util/config/SingleConfigurableTask.java
This PR solves [IZPACK-1264](https://izpack.atlassian.net/browse/IZPACK-1264):
When patching numbered properties there are
- disappearing their comments
- moved to the end of the resulting file instead of beginning at the original line
- not consolidated indexes after merging, for example merging
```
prop.1
prop.2
```
to
```
prop.4
```
results in 
```
prop.1
prop.2
prop.4
```
instead of
```
prop.1
prop.2
prop.3
```
=> [IZPACK-1264] ConfigurationInstallerListener: Numbered properties not consolidated and moved to the end of the file when patching

izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/field/rule/RuleField.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/text/GUITextField.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/validator/HostAddressValidator.java
This change fixes the following issues:
- [IZPACK-1239](https://izpack.atlassian.net/browse/IZPACK-1239) UserInputPanel: HostAddressValidator not working as expected
- [IZPACK-1269](https://izpack.atlassian.net/browse/IZPACK-1269) UserInputPanel: Explicit rule field validators defined in UserInputSpec.xml are ignored
=> Sprint - Release 5.0.3

izpack-installer/src/main/java/com/izforge/izpack/installer/data/UninstallDataWriter.java
Console uninstaller depends on jline. It had to be written to uninstaller JAR. This fixes console uninstaller not working. I elaborated on this bug here: https://groups.google.com/forum/#!topic/izpack-dev/A7nR6In_XC4
=> Added console uninstaller dependency

izpack-panel/src/main/java/com/izforge/izpack/panels/htmllicence/HTMLLicencePanel.java
add support for an installer using multiple HTMLLicencePanels, by
specifying a per-ID html file to load.
This solves https://izpack.atlassian.net/browse/IZPACK-1256 for me.
=> support multiple HTMLLicencePanels

izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/UserInputPanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/field/FieldFactory.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/field/rule/RuleField.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/text/GUITextField.java, izpack-panel/src/test/java/com/izforge/izpack/panels/userinput/console/rule/ConsoleRuleFieldTest.java, izpack-panel/src/test/java/com/izforge/izpack/panels/userinput/field/rule/RuleFieldValidatorTest.java, izpack-panel/src/test/java/com/izforge/izpack/panels/userinput/gui/rule/GUIRuleFieldTest.java
This one is to solve [IZPACK-1284](https://izpack.atlassian.net/browse/IZPACK-1284):
Provided a definition like this:
install.xml:
```xml
<variable name="appserver.port" value="8080" condition="TomcatSelected" />
<variable name="appserver.port" value="50000" condition="NetweaverSelected" />
```
userInputSpec.xml:
```xml
<panel id="panel.appserver">
...
<field type="rule" variable="appserver.port">
<spec txt="Application server port:" id="text.appserver.port" layout="N:5:5" />
...
</field>
</panel>
```
If one of both alternative conditions is true by default from the beginning, either `TomcatSelected` or `NetweaverSelected`, the variable `appserver.port` is set to the according value. Fine so far.
But if the opposite condition gets true for example as a result of a certain user input on …
=> [IZPACK-1284] Rule field value does not always show the current value of the underlying variable

izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/UserInputPanel.java
This issue concerns [https://izpack.atlassian.net/browse/IZPACK-1285](IZPACK-1285) has been introduced with [https://izpack.atlassian.net/browse/IZPACK-1284](IZPACK-1284):
Some panels are not rendered correctly after being activated the first time, there are missing fields which appear after pressing Next and Previous subsequentially.
Apologises. Fix will be released soon.
=> [IZPACK-1285] UserInputPanel: Fields not rendered after activating panel the first time

izpack-installer/src/main/java/com/izforge/izpack/util/os/Shortcut.java, izpack-installer/src/main/java/com/izforge/izpack/util/os/Unix_Shortcut.java, izpack-installer/src/main/java/com/izforge/izpack/util/os/Win_Shortcut.java, izpack-installer/src/test/java/com/izforge/izpack/util/InstallerTargetPlatformFactoryTest.java, izpack-panel/src/main/java/com/izforge/izpack/panels/shortcut/ShortcutPanelLogic.java
This is a fix for https://izpack.atlassian.net/browse/IZPACK-1297.
There has been a missing override in com.izforge.izpack.util.os.Unix_Shortcut, which prevented to gather the icon filename completely in UNIX.
=> [IZPACK-1297] Linux Shortcuts not installed when run as sudo

izpack-compiler/pom.xml, izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java, izpack-compiler/src/main/java/com/izforge/izpack/compiler/helper/CompilerHelper.java, izpack-compiler/src/main/java/com/izforge/izpack/compiler/packager/impl/PackagerBase.java, izpack-compiler/src/main/resources/schema/5.0/izpack-antactions-5.0.xsd, izpack-compiler/src/main/resources/schema/5.0/izpack-compilation-5.0.xsd, izpack-compiler/src/main/resources/schema/5.0/izpack-configurationactions-5.0.xsd, izpack-compiler/src/main/resources/schema/5.0/izpack-icons-5.0.xsd, izpack-compiler/src/main/resources/schema/5.0/izpack-installation-5.0.xsd, izpack-compiler/src/main/resources/schema/5.0/izpack-processing-5.0.xsd, izpack-compiler/src/main/resources/schema/5.0/izpack-registry-5.0.xsd, izpack-compiler/src/main/resources/schema/5.0/izpack-shortcuts-5.0.xsd, izpack-compiler/src/main/resources/schema/5.0/izpack-types-5.0.xsd, izpack-compiler/src/main/resources/schema/5.0/izpack-userinput-5.0.xsd, izpack-installer/src/main/java/com/izforge/izpack/installer/console/AbstractConsolePanel.java, izpack-installer/src/main/java/com/izforge/izpack/installer/console/ConsoleInstaller.java, izpack-installer/src/main/java/com/izforge/izpack/installer/console/ConsolePanel.java, izpack-installer/src/main/java/com/izforge/izpack/installer/console/ConsolePanels.java, izpack-installer/src/main/java/com/izforge/izpack/installer/panel/AbstractPanelView.java, izpack-installer/src/main/java/com/izforge/izpack/installer/panel/AbstractPanels.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/UserInputConsolePanel.java, izpack-test/src/test/java/com/izforge/izpack/integration/ExecutableFileTest.java, izpack-test/src/test/java/com/izforge/izpack/integration/IzpackInstallationTest.java, izpack-util/pom.xml, izpack-util/src/main/java/com/izforge/izpack/util/Console.java, pom.xml
Current changes:
- XSD fix: Added missing optional 'unset' attribute to dynamic variable declaration. This has been also applied to the website: http://izpack.org/schema/5.0/izpack-types-5.0.xsd.
- [IZPACK-1307](https://izpack.atlassian.net/browse/IZPACK-1307) - New LicenceConsolePanel pagination does not work reliably for long lines
- Fixed formatting
- Added word breaks for license text in console mode depending on the terminal width
- Replaced commons-lang 2.6 by commons-lang3 3.4 for new framework features
- Increased JLine version to latest 2.13
- [IZPACK-1302](https://izpack.atlassian.net/browse/IZPACK-1302) - Bad message from console installer when pressing CTRL-C in TargetPanel
=> IzPack 5.0.7 - main branch

izpack-api/src/main/java/com/izforge/izpack/api/data/LookAndFeels.java, izpack-compiler/pom.xml, izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java, izpack-installer/src/main/java/com/izforge/izpack/installer/bootstrap/InstallerGui.java, izpack-installer/src/main/java/com/izforge/izpack/installer/container/impl/GUIInstallerContainer.java, izpack-installer/src/main/java/com/izforge/izpack/installer/container/provider/GUIInstallDataProvider.java, izpack-installer/src/main/java/com/izforge/izpack/installer/language/LanguageDialog.java, izpack-installer/src/test/java/com/izforge/izpack/installer/language/LanguageDialogTest.java, izpack-panel/pom.xml, izpack-panel/src/test/java/com/izforge/izpack/panels/process/ProcessPanelTest.java, pom.xml
This request solves [IZPACK-1185](https://izpack.atlassian.net/browse/IZPACK-1185):
When install.xml includes
```xml
<laf name="substance"> 
<os family="windows" /> 
<os family="unix" /> 
<param name="variant" value="creme-coffee" /> 
</laf> 
```
The installer crashes with
```
24-Nov-2014 10:47:09 PM com.izforge.izpack.installer.container.provider.GUIInstallDataProvider load 
INFO: Using laf org.pushingpixels.substance.api.skin.SubstanceMistAquaLookAndFeel 
24-Nov-2014 10:47:09 PM com.izforge.izpack.installer.bootstrap.Installer start 
SEVERE: java.lang.IllegalStateException: This method must be called on the Event Dispatch Thread 
```
When the laf section is removed, the installer runs. 
Furthermore I could not get ```<laf name="liquid">``` to compile 
Failure: ```The path …
```
=> IZPACK-1185 - Substance L&F not compatible with Java 8

izpack-api/src/main/java/com/izforge/izpack/api/data/AutomatedInstallData.java, izpack-installer/src/main/java/com/izforge/izpack/installer/gui/InstallerFrame.java, izpack-installer/src/main/java/com/izforge/izpack/installer/gui/IzPanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/console/ConsoleChoiceField.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/field/Config.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/field/SimpleChoiceReader.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/radio/GUIRadioField.java
This pull request fixes [IZPACK-1314](https://izpack.atlassian.net/browse/IZPACK-1314):
UserInputPanel choice fields (radio, combo) partly badly handle pre-set values according to the documentation. In this case there are also slight differences in handling between GUI and console mode installations.
Provided a definition like this (there is some noise, but it has been my test case):
**install.xml**:
```xml
<variables>
<variable name="enabled" value="true"/>
</variables>
<conditions>
<condition type="and" id="showDataPanel">
<condition type="packselection">
<name>Pack 1</name>
</condition>
<condition type="packselection">
<name>Pack 2</name>
</condition>
</condition>
</conditions>
<resources>
<res id="userInputSpec.xml" src="@{izpack.build.directory}/userInputSpec.xml" />
</resources> …
```
=> IZPACK-1314 - UserInputPanel - choice fields (radio/combobox) badly handles pre-set values , difference between console and GUI installation mode

izpack-compiler/src/main/resources/schema/5.0/izpack-installation-5.0.xsd
In install.xml, according to the code and documentation, there is parsed an optional *allowClose* attribute in a panel definition, like this:
```xml
<panel classname="SimpleFinishPanel" allowClose="true"/>
```
The XSD is still missing this.
See https://izpack.atlassian.net/wiki/x/oYAH.
=> XSD fix: Added optional allowClose attribute to panel definition in install.xml

izpack-compiler/pom.xml, izpack-compiler/src/main/java/com/izforge/izpack/compiler/packager/impl/PackagerBase.java, izpack-tools/src/main/java/com/izforge/izpack/util/StringTool.java, izpack-util/src/main/java/com/izforge/izpack/util/Console.java
Post-fix for [IZPACK-1307](https://izpack.atlassian.net/browse/IZPACK-1307):
- Do not use WordUtils (commons-lang3) for word wrapping any longer - function does not work as expected in the LicenseConsolePanel in several tests on Linux and Windows
- Use a built-in utility method for word wrapping
=> IZPACK-1307 - New LicenceConsolePanel pagination does not work reliably for long lines

izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/UserInputConsolePanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/field/Field.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/field/check/CheckField.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/field/check/CheckFieldReader.java, izpack-panel/src/test/java/com/izforge/izpack/panels/userinput/console/check/ConsoleCheckFieldTest.java, izpack-panel/src/test/java/com/izforge/izpack/panels/userinput/field/check/TestCheckFieldConfig.java
This pull request fixes [IZPACK-1316](https://izpack.atlassian.net/browse/IZPACK-1316):
Provided something like this in *UserInputSpec.xml*:
```xml
<field type="check" variable="allow">
<spec txt="Allow something" true="false" false="true" set="true" id="text.allow" />
</field>
```
compared to
```xml
<field type="check" variable="allow">
<spec txt="Allow something" true="false" false="true" set="false" id="text.allow" />
</field>
```
For both cases, the checkbox is initially checked.
This due to the ambiguous check in the code (```value``` is the value of the *set* attribute):
```java
value.equals(trueValue) || Boolean.valueOf(value)
```
With the current implementation, there's currently no way out of this combination, because the value of set is considered as String and as Boolean type …
=> IZPACK-1316 - UserInputPanel "check" field - initial value not consistent in several combinations of true/false/set attributes in spec

izpack-installer/src/main/java/com/izforge/izpack/installer/console/AbstractTextConsolePanel.java, izpack-tools/src/main/java/com/izforge/izpack/util/StringTool.java, izpack-tools/src/main/java/com/izforge/izpack/util/WordUtil.java, izpack-util/src/main/java/com/izforge/izpack/util/Console.java
This request implements [IZPACK-1318](https://izpack.atlassian.net/browse/IZPACK-1318):
For all panel types inherited from ``AbstractTextConsolePanel``:
- LicencePanel,
- HTMLLicensePanel,
- InfoPanel,
- HTMLInfoPanel
we should make the paging and wordwrap configurable for displaying the multi-line text in console installation mode.
On some terminals might be problems with these features and furthermore, there might be a well-preformatted text content (for instance a license) which is messed up by automatic formatting, for example disappearing leading explicit whitespace characters at the beginning of some lines.
The definition should be made in install.xml using the optional ``<configuration>`` section as follows:
```xml
<panel classname="LicencePanel" id="panel.license">
<configuration> …
```
=> IZPACK-1318: [HTML]LicencePanel, [HTML]InfoPanel - make paging and wordwrap for the console installation mode configurable

izpack-api/src/main/java/com/izforge/izpack/api/rules/ComparisonOperator.java, izpack-compiler/src/main/resources/schema/5.0/izpack-types-5.0.xsd, izpack-core/src/main/java/com/izforge/izpack/core/rules/RulesEngineImpl.java, izpack-core/src/main/java/com/izforge/izpack/core/rules/process/CompareVersionsCondition.java, izpack-core/src/main/java/com/izforge/izpack/core/rules/process/CompareVersionsMajorCondition.java, izpack-core/src/test/java/com/izforge/izpack/core/rules/RulesEngineImplTest.java, izpack-core/src/test/resources/com/izforge/izpack/core/rules/conditions.xml
This request implements [IZPACK-1320](https://izpack.atlassian.net/browse/IZPACK-132):
Currently, there is implemented a condition of type "_compareversions_" which compares two version strings, that can have a different number of version parts, for example 1.0 and 1.0.1.
This condition assumes missing minor version parts to be 0 effectively, thus comparing 1.0 and 1.0.1 would result in comparing 1.0.0 and 1.0.1, thus evaluating 1.0 < 1.0.1.
For some use cases, this comparison behavior might be changed, there should be a second condition type comparing just the explicit major version parts of both operands and ignore the rest of the minor parts of the operand with more version parts, thus comparing 1.0 and 1.0.1 would result in comparing 1.0 and 1.0, thus evaluating 1.0 == 1.0.1.
The new …
=> IZPACK-1320: Add version comparison condition not assuming missing minor parts of one of the operands to be 0

izpack-api/src/main/java/com/izforge/izpack/api/data/Configurable.java, izpack-api/src/main/java/com/izforge/izpack/api/data/ConfigurationOption.java, izpack-api/src/main/java/com/izforge/izpack/api/data/Panel.java, izpack-api/src/main/java/com/izforge/izpack/api/data/PanelValidator.java, izpack-api/src/main/java/com/izforge/izpack/api/handler/DefaultConfigurationHandler.java, izpack-api/src/main/java/com/izforge/izpack/api/installer/DataValidator.java, izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java, izpack-compiler/src/main/resources/schema/5.0/izpack-installation-5.0.xsd, izpack-installer/src/main/java/com/izforge/izpack/installer/panel/AbstractPanelView.java, izpack-util/src/main/java/com/izforge/izpack/data/DefaultConfigurationHandlerAdapter.java
This request implements [IZPACK-1322](https://izpack.atlassian.net/browse/IZPACK-1322):
A custom panel validator class must currently implement the ``DataValidator`` interface.
This interface has some limitations, especially it is not possible to add parameters from install.xml dedicated to the validator. Validators implementing the ``DataValidator`` interface are forced to read the data to validate from know IzPack variables. If one needs to add static parameters, for example a minimum and maximum version for a version checker, these parameters must be set as static variables in install.xml. There cannot be explicitly seen the binding of these variables to the validator.
There should be an enhanced approach adding configuration parameters to the custom validator. Example: …
=> IZPACK-1322: Provide API for configurable validators to implementing better custom panel validators

izpack-panel/src/main/java/com/izforge/izpack/panels/htmllicence/HTMLLicenceConsolePanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/htmllicence/HTMLLicencePanel.java
This is a fix for [IZPACK-1324](https://izpack.atlassian.net/browse/IZPACK-1324):
In [pull request #364](https://github.com/izpack/izpack/pull/364), there has been introduced the support of multiple instances of HTMLLicencePanel in one installer.
Unfortunately, there has been implemented just the Swing part, the console installation mode still lacks of this feature.
Did also some code cleanup in `HTMLLicencePanel`.
=> IZPACK-1324: HTMLLicenceConsolePanel not updated to support multiple instances of HTMLLicencePanel

izpack-panel/src/main/java/com/izforge/izpack/panels/packs/PacksModel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/packs/PacksModelGUI.java, izpack-panel/src/main/java/com/izforge/izpack/panels/packs/PacksPanelBase.java, izpack-panel/src/main/java/com/izforge/izpack/panels/treepacks/TreePacksPanel.java
This is a fix for [IZPACK-1325](https://izpack.atlassian.net/browse/IZPACK-1325):
The installedPacks field is initialized only in constructor. While it is used before initialization in removeAlreadyInstalledPacks():
```
java.lang.NullPointerException
at com.izforge.izpack.panels.packs.PacksModel.removeAlreadyInstalledPacks(PacksModel.java:877)
at com.izforge.izpack.panels.packs.PacksModel.loadInstallationInformation(PacksModel.java:910)
at com.izforge.izpack.panels.packs.PacksModel.<init>(PacksModel.java:90)
at com.izforge.izpack.panels.packs.PacksModelGUI.<init>(PacksModelGUI.java:38)
at com.izforge.izpack.panels.packs.PacksPanelBase$5.<init>(PacksPanelBase.java:656)
at com.izforge.izpack.panels.packs.PacksPanelBase.panelActivate(PacksPanelBase.java:655)
at …
```
=> IZPACK-1325: NullPointerException in PacksPanelBase

izpack-installer/src/main/java/com/izforge/izpack/installer/gui/InstallerFrame.java
This fixes [IZPACK-1326](https://izpack.atlassian.net/browse/IZPACK-1326):
At the moment, during initializing an `InstallerFrame`, there is initialized the debug panel even if `-DTRACE=true` isn't set at the command line. This implies evaluating of all conditions at installer startup which cannot be prevented, because it out of the scope of the user.
This can lead to warnings and other unwanted side effects, for instance if conditions use variables, which cannot be resolved at this time.
Initialize instances of graphical debug elements only if the `-DTRACE=true` mode has been explicitly set.
=> IZPACK-1326: GUI installation mode - InstallerFrame initializes debug ger and thus triggers additional evaluating of all conditions

izpack-core/src/main/java/com/izforge/izpack/core/handler/ConsolePrompt.java, izpack-installer/src/main/java/com/izforge/izpack/installer/console/AbstractConsolePanel.java, izpack-installer/src/main/java/com/izforge/izpack/installer/console/AbstractTextConsolePanel.java, izpack-installer/src/main/java/com/izforge/izpack/installer/util/PanelHelper.java, izpack-panel/src/main/java/com/izforge/izpack/panels/checkedhello/CheckedHelloConsolePanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/defaulttarget/DefaultTargetConsolePanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/finish/FinishConsolePanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/hello/HelloConsolePanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/htmlinfo/HTMLInfoConsolePanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/install/InstallConsolePanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/installationgroup/InstallationGroupConsolePanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/jdkpath/JDKPathConsolePanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/packs/PacksConsolePanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/process/ProcessConsolePanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/shortcut/ShortcutConsolePanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/target/TargetConsolePanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/treepacks/TreePacksConsolePanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/UserInputConsolePanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userpath/UserPathConsolePanel.java, izpack-panel/src/test/java/com/izforge/izpack/panels/process/ProcessConsolePanelTest.java
This request implements [IZPACK-1327](https://izpack.atlassian.net/browse/IZPACK-1327):
Currently, no implementation of the built-in console mode panels doesn't show the panel headline like in GUI mode. In console mode, after activating a new panel, the headline should be printed to the terminal:
**Example: TargetPanel**
```
──────────────────────────────────────────────────────────
Target Path
──────────────────────────────────────────────────────────
Select the installation path:  [/home/rkrell/myapp] 
```
The _useHeadingPanel_ modifier in the `<guiprefs>` section of install.xml is ignored here, since guiprefs are not available to console panels.
=> IZPACK-1327: Print headline for all built-in console-mode panels

izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java, izpack-compiler/src/main/java/com/izforge/izpack/compiler/merge/CompilerPathResolver.java, izpack-installer/src/main/java/com/izforge/izpack/installer/util/PanelHelper.java, izpack-maven-plugin/src/main/java/org/izpack/mojo/IzPackNewMojo.java, izpack-util/src/main/java/com/izforge/izpack/util/LogFormatter.java
This is an implementation of [IZPACK-1328](https://izpack.atlassian.net/browse/IZPACK-1328):
From the mailing lists and from experience, there came several motions to improve the log output produced by the Java Util Logging system of the compiler and installer:
- Use Maven log level in IzPack Maven plugin.
- Don't log added files at INFO level, move it to DEBUG level instead.
This should help to keep the build log less messy
- As a replacement for no longer showing the single files added log a message how many files were added with each single pack.
- Shorten the log message for added files.
- Strip the `$INSTALL_PATH/` prefix from target paths logged.
- Mute meaningless log entries with stacktrace of type:
```
[FINE] No PanelAutomation + found for class …
```
=> IZPACK-1328: Various compiler and installer logging improvements

izpack-api/src/test/resources/com/izforge/izpack/api/adaptator/partial.xml, izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java, izpack-compiler/src/main/resources/schema/5.0/izpack-installation-5.0.xsd, izpack-compiler/src/test/resources/bindingTest.xml, izpack-dist/src/main/izpack/install.xml, izpack-maven-plugin/src/examples/groovy/src/izpack/install.xml, izpack-test/src/test/resources/samples/natives/natives.xml, izpack-test/src/test/resources/samples/windows/consoleinstall_alt_uninstall.xml, izpack-test/src/test/resources/samples/windows/install.xml
This request implements [IZPACK-1332](https://izpack.atlassian.net/browse/IZPACK-1332):
I stumbled upon this while reviewing and discussing issue IZPACK-1331:
There is an inaccuracy in the definition of the optional attribute stage of the <native> tag:
See https://github.com/izpack/izpack/blob/master/izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java#L666-L682:
```java
// Additionals for mark a native lib also used in the uninstaller
// The lib will be copied from the installer into the uninstaller if
// needed.
// Therefore the lib should be in the installer also it is used only
// from
// the uninstaller. This is the reason why the stage wiil be only
// observed
// for the uninstaller.
String stage = ixmlElement.getAttribute("stage");
List<OsModel> constraints …
```
=> IZPACK-1332: Ambiguous meaning of <native> attribute stage

izpack-compiler/src/main/java/com/izforge/izpack/compiler/helper/XmlCompilerHelper.java, izpack-compiler/src/main/resources/schema/5.0/izpack-installation-5.0.xsd
This is a fix for [IZPACK-1334](https://izpack.atlassian.net/browse/IZPACK-1334):
According to the documentation, https://izpack.atlassian.net/wiki/x/joAH, the `<uninstaller>` tag has in the `<info>` section has the following attributes:
- _write_ (optional, values "_yes_" or "_no_", default value "_yes_")
If yes, the uninstaller will be written.
- _path_ (optional, defaults to "_$INSTALL_PATH/Uninstaller_")
Specifies the destination path where the uninstaller jar file is written to during the installation.
- _name_ (optional, default: "_uninstaller.jar_")
Specifies the default name of the uninstaller jar generated during the installation.
- _condition_ (optional, no default)
Specifies a condition which has to be fulfilled for creating the uninstaller.
The current XSD doesn't currently …
=> IZPACK-1334: <uninstaller> tag not compiled according to documentation

izpack-core/src/main/java/com/izforge/izpack/core/rules/process/ContainsCondition.java
This fixes issue [IZPACK-1335](https://izpack.atlassian.net/browse/IZPACK-1335):
The following NPE can happen using the "contains" condition:
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
at com.izforge.izpack.core.rules.process.ContainsCondition.matchesString(ContainsCondition.java:174)
at com.izforge.izpack.core.rules.process.ContainsCondition.matchesByLine(ContainsCondition.java:147)
at com.izforge.izpack.core.rules.process.ContainsCondition.isTrue(ContainsCondition.java:131)
at com.izforge.izpack.core.rules.logic.NotCondition.isTrue(NotCondition.java:92)
at com.izforge.izpack.core.rules.process.RefCondition.isTrue(RefCondition.java:84)
at com.izforge.izpack.core.rules.logic.AndCondition.isTrue(AndCondition.java:73)
at …
```
=> IZPACK-1335: NPE in "contains" condition

izpack-compiler/src/main/resources/schema/5.0/izpack-types-5.0.xsd
Fix for [IZPACK-1337](https://izpack.atlassian.net/browse/IZPACK-1337):
The definition 
```xml
<condition id="IsEmpty" type="empty">
<string>${some var}</string>
</condition>
```
is not allowed in the XSD at this time.
Allow this to not fail during compiling in 5.0.7.
Merge this fix also to the web schema definitions.
=> IZPACK-1337: Add missing nested tag <string> to "empty" condition in XSD

izpack-compiler/src/main/resources/schema/5.0/izpack-types-5.0.xsd, izpack-core/src/main/java/com/izforge/izpack/core/data/DynamicVariableImpl.java, izpack-installer/src/main/java/com/izforge/izpack/installer/panel/AbstractPanelView.java, izpack-installer/src/main/java/com/izforge/izpack/installer/panel/AbstractPanels.java
This fixes issue [ZPACK-1338](https://izpack.atlassian.net/browse/IZPACK-1338):
The following stacktrace should be avoided.
_ignorefailure_ should be _true_ by default for dynamic variables refresh.
Instead, I saw the following stacktrace (with `-DSTACKTRACE=true`):
```
Exception in thread "AWT-EventQueue-0" com.izforge.izpack.api.exception.IzPackException: Failed to refresh dynamic variable (db.file)
at com.izforge.izpack.core.data.DefaultVariables.refresh(DefaultVariables.java:353)
at com.izforge.izpack.installer.panel.AbstractPanelView.isValid(AbstractPanelView.java:247)
at com.izforge.izpack.installer.panel.AbstractPanelView.isValid(AbstractPanelView.java:232)
at com.izforge.izpack.installer.gui.IzPanelView.isValid(IzPanelView.java:61)
at …
```
=> IZPACK-1338: Fix exception handling in installer during refreshing dynamic variables

izpack-panel/src/test/java/com/izforge/izpack/panels/target/TargetPanelHelperTest.java, izpack-util/src/main/java/com/izforge/izpack/util/file/FileUtils.java
Reverts izpack/izpack#430
Reason:
- Lets 'mvn deploy' fail on Linux:
`java.lang.AssertionError
at com.izforge.izpack.panels.target.TargetPanelHelperTest.testIsIncompatibleInstallation(TargetPanelHelperTest.java:162)`
- The new method FileUtils.createTempDir(String directory) isn't used by anone else, just by this test.
I believe this should be solved in a different way, like in https://github.com/oblac/jodd/issues/34.
Just make sure the default directory is an absolute path by using `File.getCanonicalPath()`.
=> Revert "IZPACK-1330: Fix for test errors under windows with JDK8"

izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/UserInputPanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/field/Field.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/GUIField.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/combo/GUIComboField.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/file/AbstractGUIFileField.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/file/GUIMultipleFileField.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/password/GUIPasswordGroupField.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/radio/GUIRadioField.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/rule/GUIRuleField.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/text/GUITextField.java
Implementation of a fix for [IZPACK-1339](https://izpack.atlassian.net/browse/IZPACK-1339):
Variable placeholders are not resolved in static text fields and field labels of the UserInputConsolePanel.
Added also replacement of variables in tooltips.
=> IZPACK-1339: Variables not resolved in static text fields and field labels of UserInputConsolePanel

izpack-core/src/main/java/com/izforge/izpack/core/handler/ConsolePrompt.java, izpack-installer/src/main/java/com/izforge/izpack/installer/console/AbstractConsolePanel.java, izpack-panel/src/test/java/com/izforge/izpack/panels/test/AbstractTestPanelContainer.java, izpack-test/src/test/java/com/izforge/izpack/installer/console/TestConsoleInstaller.java, izpack-util/src/main/java/com/izforge/izpack/util/Console.java
This request contains fixes for [IZPACK-1342](https://izpack.atlassian.net/browse/IZPACK-1342):
There is a few regressions within the latest console mode enhancements:
- In the fallback console installation mode (without JLine initialization using the standard Java Console), text input fields are skipped on first keystroke.
This way it is not possible to override their values, for instance the path in TargetConsolePanel.
- There are NullPointer exceptions in console fallback mode (if JLine cannot initialize the terminal).
- Panel console tests use Housekeeper instead of TestHousekeeper and let the VM crash during Maven builds with tests.
- Text lines of asterisks in console mode prompts do not adapt to the terminal width and are thus broken into multiple lines if the message is longer …
=> IZPACK-1342: Console installer regressions

izpack-test/src/test/java/com/izforge/izpack/installer/console/TestConsoleInstaller.java, izpack-util/src/main/java/com/izforge/izpack/util/Console.java
- Removed the nasty message "Could not initialize a fallback console" during console installations.
- Added forgotten commit - use TestHousekeeper to not crash tests during the build.
=> IZPACK-1342: Console installer regressions (post-fixes)

izpack-installer/src/main/java/com/izforge/izpack/installer/console/AbstractConsolePanel.java, izpack-installer/src/main/java/com/izforge/izpack/installer/console/AbstractTextConsolePanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/checkedhello/CheckedHelloConsolePanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/defaulttarget/DefaultTargetConsolePanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/finish/FinishConsolePanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/hello/HelloConsolePanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/install/InstallConsolePanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/installationgroup/InstallationGroupConsolePanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/jdkpath/JDKPathConsolePanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/packs/PacksConsolePanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/process/ProcessConsolePanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/shortcut/ShortcutConsolePanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/target/TargetConsolePanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/treepacks/TreePacksConsolePanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/UserInputConsolePanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userpath/UserPathConsolePanel.java
This request implements post-fixes for IZPACK-1327, initially implemented in #427.
Especially the `CheckedHelloConsolePanel` showed it contents including the prompt two times, which broke the `WindowsConsoleInstallationTest`.
=> IZPACK-1327: Print headline for all built-in console-mode panels (post-fixes)

izpack-compiler/src/main/java/com/izforge/izpack/compiler/packager/impl/PackagerBase.java
The compiled installer jar contains all available DLLs, flag icons and translations regardless of the choice in install.xml in a separate resource folder:
```
/com/izforge/izpack/bin/
├── langpacks
│   ├── flags
│   │   ├── bra.gif
│   │   ├── cat.gif
│   │   ├── ces.gif
│   │   ├── dan.gif
│   │   ├── deu.gif
│   │   ├── ell.gif
│   │   ├── eng.gif
│   │   ├── eus.gif
│   │   ├── fa.gif
│   │   ├── fin.gif
│   │   ├── fra.gif
│   │   ├── glg.gif
│   │   ├── hun.gif
│   │   ├── chn.gif
│   │   ├── idn.gif
│   │   ├── ita.gif
│   │   ├── jpn.gif
│   │   ├── kor.gif
│   │   ├── msa.gif
│   │   ├── nld.gif
│   │   ├── nor.gif
│   │   ├── pol.gif
│   │   ├── prt.gif
│   │   ├── ron.gif
│   │   ├── rus.gif
│   │   ├── slk.gif
│   │   ├── spa.gif
│   │   ├── srp.gif
│   │   ├── swe.gif
│   │   …
```
=> IZPACK-1346: Compiled installer contains needless resources - save size by removing them

izpack-compiler/src/main/resources/schema/5.0/izpack-compilation-5.0.xsd, izpack-compiler/src/main/resources/schema/5.0/izpack-configurationactions-5.0.xsd, izpack-compiler/src/main/resources/schema/5.0/izpack-langpack-5.0.xsd
All resource xml's should allow optional "empty" files.
See (https://izpack.atlassian.net/browse/IZPACK-1349) for details
=> IZPACK-1349: allow "empty" resource xmls

izpack-panel/src/main/java/com/izforge/izpack/panels/path/PathInputBase.java, izpack-panel/src/main/java/com/izforge/izpack/panels/path/PathInputConsolePanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/path/PathInputPanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/target/TargetConsolePanel.java, izpack-panel/src/test/java/com/izforge/izpack/panels/target/TargetConsolePanelTest.java, izpack-panel/src/test/java/com/izforge/izpack/panels/test/TestConsolePanelContainer.java, izpack-test/src/test/java/com/izforge/izpack/integration/console/ConsoleInstallationTest.java, izpack-test/src/test/java/com/izforge/izpack/integration/console/PacksConsoleInstallationTest.java, izpack-test/src/test/java/com/izforge/izpack/integration/windows/WindowsConsoleInstallationTest.java
Implementation for [IZPACK-1353](https://izpack.atlassian.net/browse/IZPACK-1353):
In TargetPanel and PathInputPanel there is a functional difference between the GUI and the console installation mode:
The configuration parameters _ShowCreateDirectoryMessage_ and _ShowExistingDirectoryWarning_ according to the [documentation](https://izpack.atlassian.net/wiki/x/eoAH) are ignored.
=> IZPACK-1353: Consolidate behavior of TargetPanel in GUI and console installation mode

izpack-installer/src/main/java/com/izforge/izpack/installer/bootstrap/InstallerConsole.java, izpack-installer/src/main/java/com/izforge/izpack/installer/bootstrap/InstallerGui.java, izpack-installer/src/main/java/com/izforge/izpack/installer/console/ConsoleInstaller.java, izpack-installer/src/main/java/com/izforge/izpack/installer/language/LanguageConsoleDialog.java, izpack-installer/src/main/java/com/izforge/izpack/installer/language/LanguageDialog.java, izpack-installer/src/test/java/com/izforge/izpack/installer/language/LanguageDialogTest.java, izpack-test/src/test/java/com/izforge/izpack/installer/console/TestConsoleInstaller.java
I'm not sure about the log message "Not all installer requirements are fulfilled." though because this is displayed even when user decides not run another instance of izpack when one is already running. Maybe this can be finetuned even more.
=> Requirements check changes across installer modes

izpack-installer/src/main/java/com/izforge/izpack/installer/bootstrap/InstallerConsole.java, izpack-installer/src/main/java/com/izforge/izpack/installer/bootstrap/InstallerGui.java
This issue improves the implementation of [IZPACK-1354](https://izpack.atlassian.net/browse/IZPACK-1354):
There is a number of installer requirement checks done before the first panel appears.
One of them is the lock check, whether the current installer is already running at the current host in another instance. 
Some more are user-defined, see https://izpack.atlassian.net/wiki/x/HYAH.
There's also a check whether the chosen language pack exists.
At the moment, these checks are executed in the language dialog for GUI and console mode installations. In case of using the `-language` command line option, this dialog is skipped and the according checks are not executed at all.  This option has been fixed recently to match the documentation.
Move the requirement checks off the language dialog …
=> IZPACK-1354: Do installer requirement checks after the language dialog has been confirmed

izpack-panel/src/main/java/com/izforge/izpack/panels/path/PathInputBase.java
Test creates a temp dir and file inside it rather than just file which fails when trying to write directly to C drive root on windows.
=> Fix for IZPACK-1355

izpack-compiler/src/main/resources/schema/5.0/izpack-installation-5.0.xsd
- IZPACK-1362: Add XSD for <executable> attributes "type" and "class"
- IZPACK-1364: <executable>: XSD is missing attribute "failure"
=> Izpack 1361: Several fixes for element <excutable>

izpack-api/src/main/java/com/izforge/izpack/api/rules/RulesEngine.java, izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java, izpack-compiler/src/main/resources/schema/5.0/izpack-types-5.0.xsd, izpack-core/src/main/java/com/izforge/izpack/core/rules/RulesEngineImpl.java
This fixes [IZPACK-1367](https://izpack.atlassian.net/browse/IZPACK-1367):
When using the following condition definition
```xml
<conditions>
<condition type="com.mycompany.myapp.izpack.conditions.IsAdminCondition" id="IsAdmin" />
...
<conditions>
```
to refer to a custom condition of mine, the compiler fails with the following message:
```
[ERROR] Failed to execute goal org.codehaus.izpack:izpack-maven-plugin:5.0.7:izpack (default-izpack) on project my-app-installer: Failure: Error in /home/rkrell/src/myapp/installer/install.xml at line 65, column 106 : javax.xml.transform.TransformerException: com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: cvc-enumeration-valid: Value 'com.mycompany.myapp.izpack.conditions.IsAdminCondition' is not facet-valid with respect to enumeration …
```
=> IZPACK-1367: Custom conditions with fully qualified path names in type no longer accepted

izpack-compiler/src/main/java/com/izforge/izpack/compiler/helper/CompilerHelper.java
minor correction, may be delayed after 5.0.7
=> IZPACK-1103: fix "Resource leak: 'jis' is not closed at this location"

izpack-util/src/main/java/com/izforge/izpack/data/PackInfo.java
see https://izpack.atlassian.net/browse/IZPACK-1360:
-  created new getter without parameter
-  marked getter with parameter as deprecated
=> IZPACK-1360: getter needs no parameter

izpack-compiler/src/main/resources/schema/5.0/izpack-userinput-5.0.xsd
The field type "_button_" is not accepted during validating the UserInputPanelSpec.xml resource.
=> IZPACK-1370: UserInputPanel: Field type "button" not accepted (by XSD)

izpack-compiler/src/main/java/com/izforge/izpack/compiler/bootstrap/CompilerLauncher.java
There are currently failing command line builds like `compile install.xml -o test.jar`:
```
{code}
-> Fatal error :
org.picocontainer.injectors.AbstractInjector$UnsatisfiableDependenciesException: com.izforge.izpack.compiler.CompilerConfig has unsatisfied dependency 'class java.util.logging.Handler' for constructor 'public com.izforge.izpack.compiler.CompilerConfig(com.izforge.izpack.compiler.data.CompilerData,com.izforge.izpack.api.substitutor.VariableSubstitutor,com.izforge.izpack.compiler.Compiler,com.izforge.izpack.compiler.helper.XmlCompilerHelper,com.izforge.izpack.compiler.data.PropertyManager,com.izforge.izpack.merge.MergeManager,com.izforge.izpack.compiler.helper.AssertionHelper,com.izforge.izpack.api.rules.RulesEngine,com.izforge.izpack.compiler.merge.CompilerPathResolver,com.izf …
```
=> IZPACK-1375: Fatal error: Missing instance of class java.util.logging.Handler for command line build

izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/GUIField.java
IZPACK-1379: Set the textpane to be not opaque to show background color.
=> IZPACK-1379: Set the textpane to be not opaque to show background color.

izpack-compiler/src/main/resources/schema/5.0/izpack-types-5.0.xsd
This is a fix for [IZPACK-1380](https://izpack.atlassian.net/browse/IZPACK-1380):
Provided the following definition:
```xml
<variable name="service.target" executable="/usr/bin/ls" type="process" ignorefailure="true" condition="izpack.linuxinstall+haveInstallPath">
<arg>-l</arg>
<arg>/etc/init.d/${service.name}</arg>
<filters>
<regex regexp=" \-> (.+)" select="\1"/>
</filters>
</variable>
```
If executed on Linux it doesn't set the variable although `${service.name}` refers to a valid service identifier.
The DEBUG log shows:
```
com.izforge.izpack.util.FileExecutor executeCommand
FINE: executeCommand
params: /usr/bin/ls
params: -l
params: /etc/init.d/MyApp
com.izforge.izpack.util.FileExecutor executeCommand
FINE: stdout:
com.izforge.izpack.util.FileExecutor executeCommand
FINE: lrwxrwxrwx …
```
=> IZPACK-1380: Dynamic variables of executable type uses stderr="true" by default

izpack-compiler/src/main/resources/schema/5.0/izpack-installation-5.0.xsd
This fixes [IZPACK-1377](https://izpack.atlassian.net/browse/IZPACK-1377):
In 5.0.7, the `<webdir>` element is no longer accepted in the `<info>` section:
```
ERROR:  'cvc-complex-type.2.4.a: contenuto non valido che inizia con l'elemento "webdir". È previsto un elemento "{appsubpath, pack200, tempdir, summarylogfilepath, uninstaller, writeinstallationinformation, rebootaction}".'
ERROR:  'com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: cvc-complex-type.2.4.a: contenuto non valido che inizia con l'elemento "webdir". È previsto un elemento "{appsubpath, pack200, tempdir, summarylogfilepath, uninstaller, writeinstallationinformation, rebootaction}".'
```
Furthermore, there is missing the 5.0 documentation for the `<webdir>` tag.
=> IZPACK-1377: XSD is missing 'webdir' element for installation descriptor

izpack-compiler/src/main/resources/schema/5.0/izpack-installation-5.0.xsd, izpack-compiler/src/main/resources/schema/5.0/izpack-types-5.0.xsd
Along with the XSD validation introduced in 5.0.7, the _os_ attribute is no longer accepted for `<parsable>`/`<executable>` tags to specify OS family
=> IZPACK-1382: "os" attribute not accepted for <parsable>/<executable> to specify OS family

izpack-compiler/src/main/resources/schema/5.0/izpack-installation-5.0.xsd
This resolves [IZPACK-1383](https://izpack.atlassian.net/browse/IZPACK-1383):
Along with the XSD validation introduced in 5.0.7, the _os_ attribute is no longer accepted for `<singlefile>`/`<file>`/`<fileset>` tags in packs to specify OS family.
=> IZPACK-1383: "os" attribute not accepted for <singlefile>/<file>/<fileset> in packs to specify OS family

izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java, izpack-event/src/main/java/com/izforge/izpack/event/ActionBase.java, izpack-util/src/main/java/com/izforge/izpack/util/helper/SpecHelper.java
This solves [IZPACK-1374](https://izpack.atlassian.net/browse/IZPACK-1374):
In _AntActionSpec.xml_ there are usually referenced packs from install.xml by the pack's {{name}} attribute.
If there is a typo in the reference value the compiled installer doesn't even fail when executing the `AntActionInstallationListener`, but just ignores all the Ant actions nested to the
```xml
<pack name="...">
...
</pack>
```
with the misspelled name.
There should be a compiler cross check to let the compilation fail if a referenced pack hasn't been defined by that name in install.xml.
Check also the _AntActionSpec.xml_ resource, whether all resources defined by the _buildresource_ attributes exist.
=> IzPackIZPACK-1374: AntActionListener - add compiler cross check whether referenced pack exists

izpack-compiler/src/main/resources/schema/5.0/izpack-installation-5.0.xsd, izpack-dist/src/main/izpack/install.xml
In our dist installer we rely on the default value of the _override_ attribute for installing files in packs:
```xml
<pack name="Core" required="yes">
<fileset dir="" targetdir="$INSTALL_PATH">
<include name="README.md"/>
<include name="LICENSE"/>
<include name="KEYS"/>
<include name="NOTICE"/>
<include name="bin/**"/>
<include name="lib/**"/>
<include name="legal/**"/>
<include name="schema/**"/>
</fileset>
...
</pack>
```
This is wrong, but the default should be at least _"update"_ (overwrite newer files). But even this probably doesn't happen, because beginning from 5.0.7, in case of not using an attribute, but this attribute is defined in the XSD with a default value, default value from the XSD is used, which is also wrong and does not match the compiler implementation for all three …
=> IZPACK-1385: Distribution installer does not overwrite existing files

izpack-compiler/src/main/resources/schema/5.0/izpack-userinput-5.0.xsd
The `<processor class="..."/>` element nested to `<field><spec>...</spec></field>` is no longer accepted when compiling the _UserInputSpec.xml_ resource.
There is a missing definition in the XSD.
=> IZPACK-1387: <processor> tag nested to field <spec> not accepted during compiling UserInputSpec.xml resource

izpack-compiler/src/main/resources/schema/5.0/izpack-installation-5.0.xsd
In a `<pack>` definition, there is not allowed the `condition` attribute for nested `<file>` and `<singlefile>` tags.
It is missing in the XSD.
=> IZPACK-1386: "condition" attribute not accepted for <file> and <singlefile> tags in packs

izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java, izpack-compiler/src/main/resources/schema/5.0/izpack-installation-5.0.xsd
The `file`, `defaultexcludes`, `casesensitive` and `followsymlinks` attributes of `<fileset>` inside `<pack>` are missing in the installation schema (`<xs:complexType name="fileSetTypeDisk">`) and cannot be used since XML is validated using schema.
Fix also the documentation at https://izpack.atlassian.net/wiki/x/W4AH.
The implementation and overall meaning of the `file` attribute along with the documentation is more than stupid. I'd prefer to remove the file attribute completely from the `<fileset>` tag because it does exactly the same as if dir was used, thus it is duplicate of `dir`.
=> IZPACK-1388: Missing attributes of <fileset> inside <pack> in installation schema

pom.xml
For changes against the previous 2.13 used in IzPack see https://github.com/jline/jline2/compare/jline-2.13...jline-2.14.1
=> Increased JLine version to latest 2.14.1

izpack-compiler/src/main/resources/schema/5.0/izpack-types-5.0.xsd
The attribute _unset_ is set to _"false"_ by default in the XSD, but should be _"true"_, like before 5.0.7 in the code. The wrong default is also active at runtime from XSD if the _unset_ attribute isn't explicitly used.
=> IZPACK-1389: Dynamic variables have attribute unset="false" by default, but should be true

izpack-util/src/main/java/com/izforge/izpack/util/Console.java, pom.xml
This fixes some small issues appeared during testing the console installation mode:
- Reverted JLine to 2.12.1 - best experience with path auto-completion (no automatic appending of spaces after pressing tab)
- Fixed line wrapping on console "message boxes"
Increased versions of reporting plugins
=> Fix some regressions in console installation mode / Update reporting plugins

izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java, izpack-compiler/src/main/resources/schema/5.0/izpack-installation-5.0.xsd
This fixes issue [IZPACK-1390](https://izpack.atlassian.net/browse/IZPACK-1390):
The following attributes are missing in the XSDs and are not recognized during compiling:
Element `pack`:
- _packImgId_
- _uninstall_ (works now also with values "true" and "false")
- _excludeGroup_
- _parent_
- _group_
Element `refpack`
- _selfcontained_
=> IZPACK-1390: Unrecognized attributes to pack and refpack elements in 5.0.7

izpack-test/src/test/resources/samples/datavalidators.xml
All tests in **/integration/** are not executed during maven build since commit 2bd7816a4cf853aa7d1ebe18f496112bbcd6fdb5 from IZPACK-1094, so the defect xml is not dtected during build.
There seem to be several (?) other problems with the implementation tests, which I do not understand yet. But at least the simple error in this xml can be fixed now.
=> fixed XML for DataValidatorTest

izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/custom/CustomInputRows.java
This is a fix for [IZPACK-1401](https://izpack.atlassian.net/browse/IZPACK-1401):
Provided the following definitions:
*UserInputSpec.xml:*
```xml
<panel id="activemq.connection.panel">
<field id="activemq.connection.panel.title" type="title"/>
<field align="left" id="activemq.connection.description" type="staticText"/>
<field type="space"/>
<field type="check" variable="activemq.cluster.use">
<spec default="false" false="false" id="activemq.cluster.use.label"
true="true" txt="Use failover connection in cluster"/>
</field>
<field type="space"/>
<field type="divider"/>
<field type="space"/>
<field conditionid="ActiveMQClusterSelected" maxRow="10" minRow="1" type="custom" variable="activemq.connection.count">
<spec>
<col>
<field type="rule" variable="activemq.connection.address">
<spec …
```
=> IZPACK-1401: GUI "custom" field doesn't show default value for "rule" subfields

izpack-installer/src/main/java/com/izforge/izpack/installer/automation/AutomatedPanels.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/UserInputPanelAutomationHelper.java
Variables are blocked when loaded from XML, changes done on userinput
panel only (same like gui and console implementation)
=> IZPACK-1412

izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/UserInputPanelAutomationHelper.java
Fix for [IZPACK-1413](https://izpack.atlassian.net/browse/IZPACK-1413):
Currently, if the user saves the auto-install.xml record at the end of the installation in the FinishPanel, there are saved variable entries for all fields of a UserInputPanel, regardless of whether they are presented to the user depending on a condition (e.g. whether they are displayed or invisible).
For invisible fields there are use empty values: `""`
This is not correct. The right record of an installation for a UserInputPanel should contain just variables of those fields which are really displayed and user-editable.
=> IZPACK-1413: UserInputPanel automation: auto-install.xml should not contain variables of fields which are not displayed

izpack-compiler/src/main/resources/schema/5.0/izpack-userinput-5.0.xsd
This is a fix for [IZPACK-1410](https://izpack.atlassian.net/browse/IZPACK-1410):
The field type button does get recognized now in 5.0.8, but not the other elements or attributes needed, such successMsg attribute for spec element, and the run element under the spec one, preventing the compiler to validate any usable definition.
=> IZPACK-1410: UserInputPanel: Attributes missing in XSD for button field

izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/field/button/ButtonFieldReader.java
Fix for [IZPACK-1414](https://izpack.atlassian.net/browse/IZPACK-1414):
Example definition from the [documentation|https://izpack.atlassian.net/wiki/x/koAH]:
```xml
<field type="button" id="pokedex.query">
<spec id="pokedex.button" successMsg="pokedex.working">
<run class="com.mtjandra.button.PokemonConnectionTest" >
<msg id="pokedex.error" name="error"/>
</run>
</spec>
</field>
```
The existance of the run class (_com.mtjandra.button.PokemonConnectionTest_ in the above example) is not checked at compile time, but the installer fails with a ClassNotFoundError.
Check whether the class is part of the installer classpath already at compile time.
=> IZPACK-1414: UserInputPanel: Check for run class of button field at compile time

izpack-core/src/main/java/com/izforge/izpack/core/rules/process/ContainsCondition.java, izpack-core/src/test/java/com/izforge/izpack/core/rules/process/ContainsConditionTest.java, izpack-core/src/test/resources/com/izforge/izpack/core/rules/process/contains.txt, izpack-core/src/test/resources/com/izforge/izpack/core/rules/process/contains_in_file.xml, izpack-core/src/test/resources/com/izforge/izpack/core/rules/process/contains_in_string.xml, izpack-core/src/test/resources/com/izforge/izpack/core/rules/process/contains_in_variable.xml
The boundaries ^ and $ did not work as supposed
=> Izpack 1408: Fix for multiline regex matches

izpack-panel/src/main/java/com/izforge/izpack/panels/treepacks/TreePacksPanel.java
TreePacksPanel counts parent pack size from selected or partially
selected packs, excluding the deselected as it was previously.
=> IZPACK-1416

pom.xml
some minor corrections for the maven-surefire-plugin
- `<exclude>`'s should be in `<excludes>`, not in `<includes>`
- replaced deprecated parameter `<forkMode>` by `<forkCount>` and `<reuseFork>`
=> Fix pom: maven-surefire-plugin

izpack-installer/src/main/java/com/izforge/izpack/installer/container/provider/AbstractInstallDataProvider.java
[IZPACK-1433](https://izpack.atlassian.net/browse/IZPACK-1433):
I replaced cleanup() with deleteOnExit(). cleanup() does nothing that create() in the line before didn't already do, so I guess it was accidentally called instead of deleteOnExit() when this mechanism was initially implemented.
=> IZPACK-1433: Global temporary folder never gets deleted

izpack-compiler/src/main/java/com/izforge/izpack/compiler/packager/impl/Packager.java, izpack-installer/src/main/java/com/izforge/izpack/installer/unpacker/AbstractPackResources.java, izpack-installer/src/main/java/com/izforge/izpack/installer/unpacker/ConsolePackResources.java, izpack-installer/src/main/java/com/izforge/izpack/installer/unpacker/GUIPackResources.java
This change solves [IZPACK-961](https://izpack.atlassian.net/browse/IZPACK-961):
The  web installation feature does not work beginning from IzPack 5 (see https://izpack.atlassian.net/wiki/x/AgBYAQ), compiling fails:
```
Exception in thread "main" java.lang.AssertionError: java.io.IOException: Stream Closed 
at org.izpack.mojo.IzPackNewMojo.execute(IzPackNewMojo.java:184) 
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101) 
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209) 
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153) 
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145) 
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProj …
```
=> IZPACK-961: IzPack 5 unable to create web installer (patch from Marco Meschieri)

izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java
This change fixes [IZPACK-1450](https://izpack.atlassian.net/browse/IZPACK-1450):
The following NPE happens when there is no `<configuration>` element nested to a panel validator extending the new PanelValidator abstract class instead of DataValidator interface:
```
[ERROR] Failed to execute goal org.codehaus.izpack:izpack-maven-plugin:5.0.10:izpack (default-izpack) on project sm-installer-server: Failure: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.izpack:izpack-maven-plugin:5.0.10:izpack (default-izpack) on project sm-installer-server: Failure
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153) …
```
=> IZPACK-1450: NPE when using validators extending PanelValidator and missing <configuration> section

izpack-compiler/src/main/resources/schema/5.0/izpack-installation-5.0.xsd
This PR fixes issue [IZPACK-1453](https://izpack.atlassian.net/browse/IZPACK-1453):
Currently, the compiler does not allow the '**os**' attribute for the `<pack>` element, like in this example:
```xml
<packs>
<pack name="WindowsPack" required="no" id="pack.windows" os="windows">
<description>Windows</description>
<fileset dir="plain/windows"/>
</pack>
<pack name="LinuxPack" required="no" id="pack.linux" os="unix">
<description>Windows</description>
<fileset dir="plain/linux"/>
</pack>
<pack name="Common" required="yes" id="pack.common">
<description>Common</description>
<fileset dir="plain/common"/>
</pack>
</packs>
```
which ends in:
```
ERROR: 'cvc-complex-type.3.2.2: Attribute 'os' is not allowed to appear in element 'pack'.'
ERROR: …
```
=> IZPACK-1453: <pack> element doesn't allow the 'os' attribute by XSD, although it is implemented

izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/UserInputPanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/field/Field.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/field/check/CheckField.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/check/GUICheckField.java
This code changes implements the following issues allong with checkbox fields in UserInputPanel definitions:
- [IZPACK-1443: Check box field - allow variable references in the set attribute value](https://izpack.atlassian.net/browse/IZPACK-1443)
- [IZPACK-1456: UserInputPanel: Check box field doesn't reflect the underlying variable value when the panel is activated](https://izpack.atlassian.net/browse/IZPACK-1456)
including small code cleanups of the dependent code.
=> IZPACK-1443/IZPACK-1456: Check box field improvements and fixes

izpack-installer/src/main/java/com/izforge/izpack/installer/panel/AbstractPanelView.java
This implementation fixes [IZPACK-1459](https://izpack.atlassian.net/browse/IZPACK-1459):
There is another NPE happening during the installation for validators extending the abstract `PanelValidator` class directly:
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
at com.izforge.izpack.installer.panel.AbstractPanelView.isValid(AbstractPanelView.java:469)
at com.izforge.izpack.installer.panel.AbstractPanelView.validateData(AbstractPanelView.java:428)
at com.izforge.izpack.installer.gui.IzPanelView.validateData(IzPanelView.java:115)
at com.izforge.izpack.installer.panel.AbstractPanelView.isValid(AbstractPanelView.java:258)
at com.izforge.izpack.installer.panel.AbstractPanelView.isValid(AbstractPanelView.java:233)
at …
```
=> IZPACK-1459: Another NPE when using validators extending PanelValidator and missing <configuration> section

izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/ces.xml, izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/deu.xml, izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/eng.xml
This change fixes [IZPACK-1460](https://izpack.atlassian.net/browse/IZPACK-1460):
In a panel validator, if a filing validation should result in a warning popup window which can be quitted by the user if he wants to ignore this, the title of the messagebox appearing is odd:
"_Validation failed - continuing installation_"
It should be rather something like:
"_Risk detected"_, "_Attention needed_"
or something similar, which is shorter (no cutting of the title for shorter message texts) and does more fit the potential situation. 
Fixed the english, german and czech translation.
Feel free to send your own translations.
=> IZPACK-1460: Misleading message "Validation failed - continuing installation"

izpack-compiler/src/main/java/com/izforge/izpack/compiler/util/AntPathMatcher.java
This change fixes [IZPACK-1298](https://izpack.atlassian.net/browse/IZPACK-1298):
If you use something like
```xml
<executable type="bin" stage="never">
<fileset targetdir="${INSTALL_PATH}">
<include name="**/*.sh"/>
</fileset>
</executable>
```
and the file expected to be marked executable is directly in `${INSTALL_PATH}` it is ignored. If the according file is in a subdirectory of `${INSTALL_PATH}` it gets included.
The reason is a bad regular expression internally built in `AntPathMatcher` for this: `${INSTALL_PATH}/.*/*.sh` which matches just files in subdirectories of the installation path.
Parsables with filesets are affected as well.
=> IZPACK-1298: <executable> with <fileset> do not update executable file mode

izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/ces.xml
This change fixes [IZPACK-1463](https://izpack.atlassian.net/browse/IZPACK-1463):
The SummaryPanel has no czech translations.
This results in complete empty contents (even no label or title when displayed). In comparison, the same installer shows all contents correctly run with the english language choice.
=> IZPACK-1463: Missing translations and empty contents for SummaryPanel in czech installer language

izpack-installer/src/main/java/com/izforge/izpack/util/os/Shortcut.java, izpack-installer/src/main/java/com/izforge/izpack/util/os/Unix_Shortcut.java, izpack-installer/src/main/java/com/izforge/izpack/util/os/Win_Shortcut.java
This implementation fixes [IZPACK-1462](https://izpack.atlassian.net/browse/IZPACK-1462):
The code for UNIX shortcut handling has several minor issues:
- PNG files are broken after copying to the user's pixmaps directory.
- User shortcuts on the desktop are duplicated for each call, because they get added a timestamp to the filename each time. This results in adding one and the same shortcut again to the desktop for each installer execution.
- There is unused code and code which can be replaced by using utility methods of the Apache commons-io library which is part of each installer in IzPack 5.
- Automatic code inspection of `com.izforge.izpack.util.os.Unix_Shortcut` complains about potential bugs (NPEs and more) and incomplete comments.
=> IZPACK-1462: Issues in UNIX shortcut handling - code review

izpack-api/src/main/java/com/izforge/izpack/api/data/Overrides.java, izpack-api/src/main/java/com/izforge/izpack/api/data/VariableMapper.java, izpack-api/src/main/java/com/izforge/izpack/api/data/Variables.java, izpack-core/src/main/java/com/izforge/izpack/core/data/DefaultOverrides.java, izpack-core/src/main/java/com/izforge/izpack/core/data/DefaultVariables.java, izpack-core/src/test/java/com/izforge/izpack/core/data/DefaultVariablesTest.java, izpack-core/src/test/java/com/izforge/izpack/core/data/UpperCaseTestVariableMapper.java, izpack-core/src/test/resources/com/izforge/izpack/core/data/test.defaults, izpack-installer/src/main/java/com/izforge/izpack/installer/automation/PanelAutomation.java, izpack-installer/src/main/java/com/izforge/izpack/installer/bootstrap/Installer.java, izpack-installer/src/main/java/com/izforge/izpack/installer/bootstrap/InstallerConsole.java, izpack-installer/src/main/java/com/izforge/izpack/installer/bootstrap/InstallerGui.java, izpack-panel/src/main/java/com/izforge/izpack/panels/compile/CompilePanelAutomationHelper.java, izpack-panel/src/main/java/com/izforge/izpack/panels/defaulttarget/DefaultTargetPanelAutomationHelper.java, izpack-panel/src/main/java/com/izforge/izpack/panels/finish/FinishPanelAutomation.java, izpack-panel/src/main/java/com/izforge/izpack/panels/hello/HelloPanelAutomation.java, izpack-panel/src/main/java/com/izforge/izpack/panels/install/InstallPanelAutomationHelper.java, izpack-panel/src/main/java/com/izforge/izpack/panels/installationgroup/InstallationGroupPanelAutomationHelper.java, izpack-panel/src/main/java/com/izforge/izpack/panels/jdkpath/JDKPathPanelAutomationHelper.java, izpack-panel/src/main/java/com/izforge/izpack/panels/packs/PacksPanelAutomationHelper.java, izpack-panel/src/main/java/com/izforge/izpack/panels/process/ProcessPanelAutomation.java, izpack-panel/src/main/java/com/izforge/izpack/panels/shortcut/ShortcutPanelAutomationHelper.java, izpack-panel/src/main/java/com/izforge/izpack/panels/target/TargetPanelAutomation.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/UserInputPanelAutomationHelper.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userpath/UserPathPanelAutomationHelper.java
This is an implementation of [IZPACK-1436](https://izpack.atlassian.net/browse/IZPACK-1436):
Along with reading (and possible writing) of default values from/to a file there should be a possibility to map key names and values from the file to the installer and vice versa.
Example:
Your installer has a panel gathering a (plain) password and assigning it to the internal variable app.server.pass.plain. The key name should be more user-friendly in the defaults file and furthermore the password held as plain string in the installer should be encrypted in the defaults file, while decrypting it on the fly when reading it. Thus there should be a double mapping:
Reading defaults:
- key name: Application Password ==> app.server.pass.plain
- key value: some_encrypted_text ==> (decrypt mapper) ==> …
=> IZPACK-1436: Add default value mappers for reading from (or saving to the file)

izpack-core/src/main/java/com/izforge/izpack/core/rules/process/ContainsCondition.java, izpack-core/src/main/java/com/izforge/izpack/core/rules/process/EmptyCondition.java, izpack-core/src/main/java/com/izforge/izpack/core/rules/process/ExistsCondition.java
Imagine you have property e.g. property INSTALL_PATH set to C:/test and a file test.txt exists in C: root.
When you use exists condition it is not able to create a canonical path if you set it like this
```xml
<condition type="exists" id="DoesNotWork">
<file>${INSTALL_PATH}/../test.txt</file>
</condition>
```
it is evaluated as false.
When you set it like
```xml
<condition type="exists" id="Works">
<file>C:/test.txt</file>
</condition>
```
it is true.
=> IZPACK-1466: Non-canonical paths do not work in exists condition

izpack-installer/src/main/java/com/izforge/izpack/installer/gui/DefaultNavigator.java, izpack-installer/src/main/java/com/izforge/izpack/installer/gui/InstallerFrame.java, izpack-installer/src/main/java/com/izforge/izpack/installer/panel/AbstractPanels.java, izpack-installer/src/main/java/com/izforge/izpack/installer/panel/Panels.java, izpack-installer/src/test/java/com/izforge/izpack/installer/gui/DefaultNavigatorTest.java
This change fixes [IZPACK-1464](https://izpack.atlassian.net/browse/IZPACK-1467):
This bug has been found while implementing a fix for [IZPACK-1464](https://izpack.atlassian.net/browse/IZPACK-1464).
If a panel implementation calls `com.izforge.izpack.installer.gui.InstallerFrame#lockNextButton(true)` during the execution of the `com.izforge.izpack.panels.userinput.UserInputPanel#panelActivate` event this can lead to a deadlock in GUI mode - the first panel appears empty, the Next button is disabled and the Quit button enabled. If pressing Quit this results in a stack trace:
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
at com.izforge.izpack.installer.gui.InstallerFrame.quit(InstallerFrame.java:654)
at com.izforge.izpack.installer.gui.DefaultNavigator.quit(Defaul …
```
=> IZPACK-1467: Possible deadlock in GUI mode if Next button is locked from a panel implementation

izpack-gui/src/main/java/com/izforge/izpack/gui/LabelFactory.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/console/ConsoleField.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/console/ConsoleInputField.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/console/staticText/ConsoleStaticText.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/console/title/ConsoleTitleField.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/field/Config.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/field/Field.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/GUIField.java, izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/file/MultipleFileInputField.java
This PR solves [IZPACK-1468](https://izpack.atlassian.net/browse/IZPACK-1468):
Provided the following example:
*install.xml:*
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<izpack:installation version="5.0" xmlns:izpack="http://izpack.org/schema/installation" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://izpack.org/schema/installation http://izpack.org/schema/5.0/izpack-installation-5.0.xsd">
<info>
<appname>Test</appname>
<appversion>1.0</appversion>		
</info>
<guiprefs width="800" height="600" resizable="yes" />
<locale>
<langpack iso3="eng" />
</locale>
<resources>
<res id="userInputSpec.xml" src="userInputSpec.xml"/>
</resources>
<variables>
<variable name="p2" value="initialized" />
</variables>
<panels>
<panel …
```
=> IZPACK-1468: Variable references in labels, descriptions, statictext fields and field tooltips are resolved just during initialization

izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java, izpack-compiler/src/main/java/com/izforge/izpack/compiler/packager/impl/MultiVolumePackager.java, izpack-compiler/src/main/java/com/izforge/izpack/compiler/packager/impl/Packager.java, izpack-compiler/src/main/java/com/izforge/izpack/compiler/packager/impl/PackagerBase.java, izpack-event/src/main/java/com/izforge/izpack/event/AntActionUninstallerListener.java, izpack-event/src/main/java/com/izforge/izpack/event/RegistryInstallerListener.java, izpack-event/src/test/java/com/izforge/izpack/event/AntActionInstallerListenerTest.java, izpack-installer/src/test/java/com/izforge/izpack/installer/multiunpacker/MultiVolumeFileUnpackerTest.java, izpack-installer/src/test/java/com/izforge/izpack/installer/unpacker/AbstractFileUnpackerTest.java, izpack-installer/src/test/java/com/izforge/izpack/installer/unpacker/DefaultFileUnpackerTest.java, izpack-installer/src/test/java/com/izforge/izpack/installer/unpacker/Pack200FileUnpackerTest.java, izpack-test/src/test/java/com/izforge/izpack/integration/UninstallHelper.java, izpack-util/src/main/java/com/izforge/izpack/util/IoHelper.java, izpack-util/src/main/java/com/izforge/izpack/util/Librarian.java
This implementation solves both, [IZPACK-1479](https://izpack.atlassian.net/browse/IZPACK-1479) and [IZPACK-1480](https://izpack.atlassian.net/browse/IZPACK-1480):
**IZPACK-1479:**
Since we include Apache _commons.io_ directly to the IzPack installer we can now reduce the old codebase by using it instead of having many duplicate code around.
The next step is replacing many of the utility methods in `IOHelper`.
**IZPACK-1480:**
To avoid overwriting of resources with translations with the same ID in their <res> definition the compiler does not allow duplicate translation resources IDs any longer.
If a duplicate ID is detected, the compilation should fail, for example:
_Failure during compilation process: Unable to merge multiple packsLang.xml files: Resource 'packsLang.xml_eng' has been …
=> IZPACK-1479 + IZPACK-1480

izpack-installer/src/main/java/com/izforge/izpack/installer/container/provider/IconsProvider.java, izpack-installer/src/main/java/com/izforge/izpack/installer/unpacker/GUIPackResources.java
This PR solves [IZPACK-1481](https://izpack.atlassian.net/browse/IZPACK-1481):
At the moment, each time an installer generated by IzPack is run, there is a warning shown at the console output:
_Resource customicons.xml not defined. No custom icons available._
This is not necessary, customizing installer icons is not required at all and a rare use case.
Move this to debug log level to not show this by default.
=> IZPACK-1481: Avoid warning: "Resource customicons.xml not defined. No custom icons available"

izpack-api/src/main/java/com/izforge/izpack/api/config/Options.java, izpack-api/src/main/java/com/izforge/izpack/api/config/spi/OptionsBuilder.java, izpack-util/src/main/java/com/izforge/izpack/util/config/SingleConfigurableTask.java, izpack-util/src/test/java/com/izforge/izpack/util/config/SingleConfigurableTaskTest.java
When using the [ConfigurationInstallerListener|(https://izpack.atlassian.net/wiki/x/2IAH), it is currently able to automatically handle auto-numbered properties, which is a set of property keys beginning with the same prefix and ending on _`.<integer>`_, where _`<integer>`_ is a continuous interval of integer numbers.
Example:
```
database.cluster.host.0
database.cluster.host.1
```
If read from a property files, the prefix is taken as the property key itself and the whole set of property keys starting on it are handled as once.
This operation can be used for instance for keeping all values of the whole set or deleting them as once action in one line in ConfigurationActionSpec.xml.
Enhance the auto-numbering handling of this feature also for embedded integers, for example:
``` …
```
=> IZPACK-1482: ConfigurationInstallerListener - handle auto-numbered key-value-pairs also for numbers embedded into the key name

izpack-compiler/src/main/java/com/izforge/izpack/compiler/data/PropertyManager.java, izpack-compiler/src/main/resources/schema/5.0/izpack-installation-5.0.xsd
This PR fixes [IZPACK-1483](https://izpack.atlassian.net/browse/IZPACK-1483):
The features of the `<properties>` tag in install.xml have been cut down in IzPack 5 in comparison to version 4.
The code was able to read properties also from environment variables or a file at compile time, but it was partly buggy and the XSD did no longer allow the attributes mentioned in the [documentation(https://izpack.atlassian.net/wiki/x/m4AH]).
Fix the `<properties>` tag and make the documentation consistent again.
=> IZPACK-1483: Fix <properties> tag parsing and handling

izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java, izpack-event/src/main/java/com/izforge/izpack/event/ActionBase.java, izpack-event/src/main/java/com/izforge/izpack/event/AntAction.java, izpack-event/src/main/java/com/izforge/izpack/event/AntActionInstallerListener.java, izpack-event/src/main/java/com/izforge/izpack/event/BSFInstallerListener.java, izpack-event/src/main/java/com/izforge/izpack/event/ConfigurationInstallerListener.java, izpack-event/src/main/java/com/izforge/izpack/event/RegistryInstallerListener.java, izpack-event/src/test/java/com/izforge/izpack/event/BSFInstallerListenerTest.java, izpack-event/src/test/java/com/izforge/izpack/event/BSFUninstallerListenerTest.java, izpack-util/src/main/java/com/izforge/izpack/util/helper/SpecHelper.java
This PR resolves [IZPACK-1488](https://izpack.atlassian.net/browse/IZPACK-1488):
If using AntActionInstallerListener with an AntActionSpec.xml resource containing variable references, and a variable in these references has the '`&`' character as value at the listener execution time, the installer fails with this stacktrace:
```
/usr/java/jdk1.8.0_121/jre/bin/java -DSTACKTRACE=true -jar installer-1.0.0-SNAPSHOT.jar 
Logging initialized at level 'INFO'
Commandline arguments: 
Detected platform: suse_linux,version=4.9.5-2.g9bb1a8a-default,arch=x64,symbolicName=null,javaVersion=1.8.0_121
ERROR:  'The entity name must immediately follow the '&' in the entity reference.'
ERROR:  'com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: The entity name must immediately follow the '&' in …
```
=> IZPACK-1488: AntActionInstallerListener action fails if it contains a variable reference containing a '&' character in its value at runtime

izpack-compiler/src/main/resources/schema/5.0/izpack-configurationactions-5.0.xsd
This PR fixes [IZPACK-1490](https://izpack.atlassian.net/browse/IZPACK-1490):
According to the [documentation|https://izpack.atlassian.net/wiki/x/2IAH] it should be possible to define nested, local variables for each configuration action:
```xml
<configuration_action_tag>
<variables>
<variable/>
<variable/>
... 
</variables>
</configuration_action_tag>
```
Although this is already implemented a long time, the XSD for the configuration action resource doesn't allow these variable definitions any longer since validation has been automatically activated for the compilation process.
=> IZPACK-1490: ConfigurationActionListener: <variables> tag not accepted during compilation

izpack-api/src/main/java/com/izforge/izpack/api/config/Options.java, izpack-util/src/test/java/com/izforge/izpack/util/config/SingleConfigurableTaskTest.java
Post-fix for [IZPACK-1482](https://izpack.atlassian.net/browse/IZPACK-1482) solved in #566 found recently:
Options have been mapped badly during saving the target Options, for example `param.1.opt.1` -> `param1opt.1`.
Added also a unit test for avoiding this in future.
=> IZPACK-1482: ConfigurationInstallerListener - handle auto-numbered key-value-pairs also for numbers embedded into the key name (post-fix)

izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java, izpack-compiler/src/main/resources/schema/5.0/izpack-installation-5.0.xsd
This fixes [IZPACK-1476](https://izpack.atlassian.net/browse/IZPACK-1476):
XML Schema does not permit the use of the uninstaller="true" attribute in the run-privileged element. See [this discussion](https://groups.google.com/forum/#!topic/izpack-user/W8wJA5ihqmc) for details.
=> IZPACK-1476: XML Schema does not allow uninstaller attribute in run-privileged element

izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java, izpack-compiler/src/main/resources/schema/5.0/izpack-installation-5.0.xsd, izpack-installer/src/main/java/com/izforge/izpack/installer/unpacker/UnpackerBase.java, izpack-installer/src/main/java/com/izforge/izpack/util/LogUtils.java
Enhancement of the implementation for [IZPACK-1472](https://izpack.atlassian.net/browse/IZPACK-1472):
Added `mkdirs` compile-time attribute.
Also improved the XSD inline documentation a bit.
Some bug fixes and cleanup to make it consistent with the LogManager API.
=> IZPACK-1472: Introduce customizable installer logging (continuation)

izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java, izpack-compiler/src/main/resources/schema/5.0/izpack-installation-5.0.xsd
This is an implementation of [IZPACK-1493](https://izpack.atlassian.net/browse/IZPACK-1493):
Enhance the <file> tag in <pack> by the following features:
- auto-recognize compression and archive format (independently on the file name extension)
- add support for all compression and archive formats supported by common-compression
- add `<archivefileset>` to filter and redirect extracted contents when being added as files and directories to a pack during compiling.
=> IZPACK-1493: <file> tag: Auto-recognize archive file format and allowarchive filesets to be defined

izpack-installer/src/main/java/com/izforge/izpack/util/os/Unix_Shortcut.java
Implementation of [IZPACK-1507](https://izpack.atlassian.net/browse/IZPACK-1507):
This avoids creation of invalid `.desktop` files assuming that GNOME's `desktop-file-utils` 0.23 is the state-of-the-art check (empty `Encoding` causes invalid file and `Encoding` is deprecated, so I added a warning).
=> IZPACK-1507: Handling deprecation of Encoding entry

izpack-installer/src/main/java/com/izforge/izpack/util/os/Unix_Shortcut.java, izpack-installer/src/test/java/com/izforge/izpack/util/os/Unix_ShortcutTest.java
This is a fix for [IZPACK-1508](https://izpack.atlassian.net/browse/IZPACK-1508):
During shortcut creation, remove default quoting of Exec value with '' because it prevents valid .desktop files to be created; escaping should be handled by the user.
=> IZPACK-1508: Removed default quoting of Exec value with ''

izpack-installer/src/main/java/com/izforge/izpack/installer/bootstrap/InstallerGui.java
This one solves [IZPACK-1471](https://izpack.atlassian.net/browse/IZPACK-1471):
org.pushingpixels.substance.api.UiThreadingViolationException: State tracking must be done on Event Dispatch Thread
at org.pushingpixels.substance.internal.animation.StateTransitionTracker$ModelStateInfo.clear(StateTransitionTracker.java:166)
at org.pushingpixels.substance.internal.animation.StateTransitionTracker.setModel(StateTransitionTracker.java:295)
at org.pushingpixels.substance.internal.utils.ButtonVisualStateTracker$2.propertyChange(ButtonVisualStateTracker.java:104)
at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.ja …
=> IZPACK-1471: UiThreadingViolationException when using substance laf

izpack-api/src/main/java/com/izforge/izpack/api/data/PackFile.java, izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java, izpack-compiler/src/main/java/com/izforge/izpack/compiler/data/CompilerData.java, izpack-compiler/src/main/java/com/izforge/izpack/compiler/packager/impl/Packager.java, izpack-installer/src/main/java/com/izforge/izpack/installer/multiunpacker/MultiVolumeFileUnpacker.java, izpack-installer/src/main/java/com/izforge/izpack/installer/multiunpacker/MultiVolumeUnpacker.java, izpack-installer/src/main/java/com/izforge/izpack/installer/unpacker/CompressedFileUnpacker.java, izpack-installer/src/main/java/com/izforge/izpack/installer/unpacker/DefaultFileUnpacker.java, izpack-installer/src/main/java/com/izforge/izpack/installer/unpacker/FileUnpacker.java, izpack-installer/src/main/java/com/izforge/izpack/installer/unpacker/LooseFileUnpacker.java, izpack-installer/src/main/java/com/izforge/izpack/installer/unpacker/Pack200FileUnpacker.java, izpack-installer/src/main/java/com/izforge/izpack/installer/unpacker/UnpackerBase.java, izpack-installer/src/test/java/com/izforge/izpack/installer/multiunpacker/MultiVolumeFileUnpackerTest.java, izpack-installer/src/test/java/com/izforge/izpack/installer/unpacker/AbstractFileUnpackerTest.java, izpack-installer/src/test/java/com/izforge/izpack/installer/unpacker/DefaultFileUnpackerTest.java, izpack-installer/src/test/java/com/izforge/izpack/installer/unpacker/LooseFileUnpackerTest.java, izpack-installer/src/test/java/com/izforge/izpack/installer/unpacker/Pack200FileUnpackerTest.java, izpack-util/src/main/java/com/izforge/izpack/util/NoCloseInputStream.java, izpack-util/src/main/java/com/izforge/izpack/util/NoCloseOutputStream.java
This is especially a fix for [IZPACK-1497](https://izpack.atlassian.net/browse/IZPACK-1497), provided as part of [IZPACK-1495](https://izpack.atlassian.net/browse/IZPACK-1495):
- Backreferences where totally broken
- Stabilized commons-compress and pack200 and mixes of them, more tests
- Fixed scope of pack compression setting
- Improved Pack200 unit test
=> IZPACK-1497:  Serialize actual size of packed file data instead of the size of the original file to enable compression

izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java, izpack-compiler/src/main/resources/schema/5.0/izpack-installation-5.0.xsd, izpack-compiler/src/main/resources/schema/5.0/izpack-types-5.0.xsd, izpack-installer/src/main/java/com/izforge/izpack/installer/bootstrap/Installer.java, izpack-installer/src/main/java/com/izforge/izpack/installer/unpacker/UnpackerBase.java, izpack-installer/src/main/java/com/izforge/izpack/util/LogUtils.java, izpack-installer/src/main/resources/com/izforge/izpack/installer/logging/logging.base.properties
Post-fixes for [IZPACK-1472(https://izpack.atlassian.net/browse/IZPACK-1472):
- Allow to define a console log level (incl. muting it)
- Fixes regarding mixing of log levels between the console and file handlers
=> IZPACK-1472: Introduce customizable installer logging

izpack-compiler/pom.xml, izpack-compiler/src/main/java/com/izforge/izpack/compiler/packager/impl/PackagerBase.java, izpack-maven-plugin/pom.xml
This change fixes [IZPACK-1510](https://izpack.atlassian.net/browse/IZPACK-1510):
We are still packing the retired jakarta-regexp 1.4 (org/apache/regexp) to the installer by default, which is never used by the default at runtime any longer. We use java.util.regexp and encourage custom implementation to do the same. We can remove it to reduce the size of the installer.
Along with this, remove also the compile-time dependency of the compiler to Apache BCEL (which also refers to Apache Regex), it should has scope test only.
=> IZPACK-1510: Remove dependency and packaging of jakarta-regexp to installer

pom.xml
This change updates some dependencies:
- [IZPACK-1511](https://izpack.atlassian.net/browse/IZPACK-1511): Update picocontainer to 2.15
Picocontainer 2.15 has been released already some time ago (since they moved from Codehaus to Github):
https://github.com/picocontainer/PicoContainer2
We should use go for it in this major release.
- [IZPACK-1512](https://izpack.atlassian.net/browse/IZPACK-1512): Update Apache Ant dependency to 1.9.9
Apache Ant is currently at 1.9.9 (which is the latest release still supporting JDK 5 and 6).
This shouldn't probably break anything but I rather mark breaking. Check your usecases or fix your old version in your local dependency management.
We should use go for it in this major release.
=> IZPACK-1511 + IZPACK-1512: Update dependencies - picocontainer 2.15, Apache Ant 1.9.9

izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java, izpack-util/pom.xml, izpack-util/src/main/java/com/izforge/izpack/util/compress/ArchiveStreamFactory.java, izpack-util/src/main/java/com/izforge/izpack/util/compress/SevenZArchiveInputStream.java, pom.xml
This is a fix for [IZPACK-1515](https://izpack.atlassian.net/browse/IZPACK-1515):
Adding 7z file to be unpacked gives error during compile.
```xml
<file src="some-file.7z" targetdir="${INSTALL_PATH}/${ZOOKEEPER_PATH}" override="true" unpack="true"/>
```
results in
```
Failed to execute goal org.codehaus.izpack:izpack-maven-plugin:5.1.0-RC3:izpack (default-izpack) on project our-project: Failure during compilation process: No compression or archiving format detected for file some-file.7z marked to be unpacked.
```
=> IZPACK-1515: Unpacking 7z does not work

izpack-compiler/pom.xml, izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java, izpack-compiler/src/main/java/com/izforge/izpack/compiler/util/compress/ArchiveStreamFactory.java, izpack-util/pom.xml
[IZPACK-1515](https://izpack.atlassian.net/browse/IZPACK-1515):
- Post-fix: Move dependency to Apache Tika to izpack-compiler (from izpack-util)
The solution for this issue pulled in a dependency to Apache Tika also to the installer, although the class making usage of Tika is only used in the compiler at the moment. Move the appropriate code and its dependencies to Apache Tika to the compiler module.
=> IZPACK-1515: unpack of 7z does not work (post-fixes)

izpack-compiler/pom.xml
This is an implementation of [IZPACK-1517](https://izpack.atlassian.net/browse/IZPACK-1517):
The standalone compiler jar has been blown up since 5.1 due to the mass of more dependencies. We don't want to deploy such an "UBER" jar to Maven Central any longer.
Furthermore, building this standalone jar significantly slows down the compilation.
Instead, we'll put building it to a Maven profile. Whoever needs it will be able to build the standalone compiler jar by activating this profile in his/her local build.
In future, activate the profile _**build-standalone-jar**_ in your local build to produce the standalone compiler jar, for instance:
```
mvn -P build-standalone-jar clean package
```
=> IZPACK-1517: Remove standalone compiler jar from officially deployed artifacts

izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java
This is a fix for [IZPACK-1440](https://izpack.atlassian.net/browse/IZPACK-1440):
The error occurs when changing the pack in the example of [IZPACK-1258](https://izpack.atlassian.net/browse/IZPACK-1258) to:
```xml
<pack name="TestLoose" required="yes" loose="true">
<description>Test the loose arg.</description>
<file src="..\..\resources\test.zip" unpack="true" targetdir="${INSTALL_PATH}\testloosepack\" />
</pack>
```
The stacktrace:
```
com.izforge.izpack.api.exception.InstallerException: Failed to unpack pack: TestLoose
at com.izforge.izpack.installer.unpacker.UnpackerBase.unpack(UnpackerBase.java:501)
at com.izforge.izpack.installer.unpacker.UnpackerBase.unpack(UnpackerBase.java:430)
at com.izforge.izpack.installer.unpacker.UnpackerBase.unpack(UnpackerBase.java:251)
at …
```
=> IZPACK-1440: Loose pack with zipfile and unpack="true" causes NPE

izpack-maven-plugin/src/main/java/org/izpack/mojo/IzPackNewMojo.java
Fix for [IZPACK-1523](https://izpack.atlassian.net/browse/IZPACK-1523):
It seems that the <enableOverrideArtifact>true</enableOverrideArtifact> element is not honored.
Just the file name is currently overridden, but the subsequent plugin (maven-install-plugin) operates upon the original artifact.
=> IZPACK-1523: <enableOverrideArtifact> true is not honored

izpack-api/src/main/java/com/izforge/izpack/api/handler/DefaultConfigurationHandler.java
Post-fix: Could not serialize panel validator implementations extending PanelValidator (DefaultConfigurationHandler serialization broken)
=> IZPACK-1535 + IZPACK-1111 (UserInputPanel field processor issues)

izpack-api/src/main/java/com/izforge/izpack/api/data/Panel.java, izpack-panel/src/test/java/com/izforge/izpack/panels/PanelDisplayTest.java
This pull request fixes the licence panel tests in PanelDisplayTest by adding a `panelId` to the panels like described in [IZPACK-1536](https://izpack.atlassian.net/browse/IZPACK-1536).
However, it does not address the issue where a licence resource is not found due to `panelId` being `null`.
=> IZPACK-1536: Fix licence panel tests in PanelDisplayTest

izpack-api/src/main/java/com/izforge/izpack/api/handler/DefaultConfigurationHandler.java, izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java
Fix for [IZPACK-1546](https://izpack.atlassian.net/browse/IZPACK-1546):
Beginning with 5.1.0, if the there are field validators used in UserInputPanel, their nested legacy `<param>` definitions are ignored a resolved as 'null' at runtime in the validator code.
This breaks for example the following definition:
```xml
<field type="rule" variable="server.address" summaryKey="key.server.address">
<spec id="text.server.address" txt="Infoserver address/port:" layout="O:15:U : N:5:5" resultFormat="displayFormat" />
<validator class="com.izforge.izpack.panels.userinput.validator.RegularExpressionValidator" txt="Invalid address or port!" id="server.address.error">
<param name="pattern" value="\b.*\:(6553[0-5]|655[0-2]\d|65[0-4]\d{2}|6[0-4]\d{3}|[1-5]\d{4}|[1-9]\d{0,3})\b" />
</validator>
</field> …
```
=> IZPACK-1546: Nested <param> tags ignored in field validator definition

izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java, izpack-compiler/src/main/resources/schema/5.0/izpack-installation-5.0.xsd
This change is a fix for [IZPACK-1363](https://izpack.atlassian.net/browse/IZPACK-1363):
If an <executable> is of type "jar", the class has to be defined mandatory.
Added this rule to the XSD for validation and added checks to CompilerConfig to avoid ambiguous usage of the `class` attribute.
=> IZPACK-1363: <executable>: attribute "class" needed, if "type" is "jar"

izpack-panel/src/main/java/com/izforge/izpack/panels/licence/AbstractLicenceConsolePanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/licence/AbstractLicencePanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/licence/LicenceLoader.java, izpack-panel/src/test/java/com/izforge/izpack/panels/licence/LicenceLoaderTest.java, izpack-panel/src/test/java/com/izforge/izpack/panels/pdflicence/PDFLicencePanelTest.java, izpack-panel/src/test/resources/com/izforge/izpack/panels/licence/LicencePanel.licence
Implementation of  [IZPACK-1548](https://izpack.atlassian.net/browse/IZPACK-1548)
This pull request also fixes the issue where a licence is not looked up with the default suffix of ".licence" if the panel identifier is `null`.
=> IZPACK-1548: Extract shared licence loading code into new class LicenceLoader

pom.xml
Implementation of  [IZPACK-1559](https://izpack.atlassian.net/browse/IZPACK-1559)
=> IZPACK-1559: Fix typo 'reuseFork' in root pom.xml

izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java
External configuration file is checked first. If it is found, it is used. Only if it is not found, all the other logging configuration logic is executed.
=> Fix IZPACK-1566: Logging from a configuration file throws exceptions

izpack-compiler/src/main/java/com/izforge/izpack/compiler/data/PropertyManager.java
The property file configured to load in izpack.xml is not able to load with the tag:
```xml
<property file="src/main/izpack/versions.properties" />
```
So far this functionality was OK, but now some regression detected.
=> fixed property file loading

izpack-util/src/main/java/com/izforge/izpack/util/TargetFactory.java
In current version of IzPack, Windows XP is considered as NT (enterprise version) Windows. This is not clear in documentation, so, to configure the resource for shortcut definition, the user generally uses:
```xml
<res id="Win_shortcutSpec.xml" src="my_windows_shortcuts.xml" />
```
This configuration works in Windows 7 but not works for Windows XP.
Some users are having problemas with this.
Is important remember that Microsoft considers Windows XP as a "domestic Windows family", while that Windows NT, 2000, 2003, etc are "NT Windows family" (enterprises Windows).
=> Fix TargetFactory for Windows XP

izpack-core/src/main/java/com/izforge/izpack/merge/resolve/PathResolver.java
Fixes `NoClassDefFoundError`-s in installer when it is compiled using Java 9.
=> Fixes IZPACK-1623 by replacing URLClassLoader.findResources

izpack-installer/src/main/java/com/izforge/izpack/installer/unpacker/UnpackerBase.java
The import of URLClassLoader caused a Classcastexception with java 9. Already resolved https://izpack.atlassian.net/browse/IZPACK-1588. But not on Github, so anyway ...
=> Deleted useless import URLClassLoader

.travis.yml, izpack-panel/src/test/java/com/izforge/izpack/panels/userinput/UserInputPanelTest.java, izpack-test/src/test/java/com/izforge/izpack/integration/InstallationTest.java
Hi,
This fixes the following issues :
1. first known error : javax.swing IllegalStateException
2. a test error
I've reactivated the GUI integration tests and it works fine for me, with JDK8 on macOS.
But, using the travis build on my repository to test on the other versions, the build fails on JDK6 only. 
It seems that the warning and error panels don't show up. But I can't reproduce the issue on my laptop with Windows and JDK6, launching one of the failing tests manually, It works fine...
I create this PR as someone else could have an idea about what's going on with JDK6...
=> IZPACK-1593: reactivate GUI integration tests

izpack-panel/src/main/java/com/izforge/izpack/panels/shortcut/ShortcutPanelLogic.java
Proposal of a fix for this bug which happens only on Unix, because of the Unix-specific "execPostAction" overriding which uses the Shortcut.UninstallerData.
When the user unchecks the checkbox on ShortcutPanel, no menu shortcut needs to be created, so the UninstallerData is not set. But we still call the "execPostAction", which makes no sense and throws the exception on Unix systems, because of the overriding mentioned earlier.
So this proposal consists of calling "execPostAction" only when the given shortcuts-to-create list is not empty.
I also added a little reorganization of shortcuts variables, as a comment wasn't actually assigned to the correct one.
=> IZPACK-1603: fix NPE on ShortcutPanel when menu shortcut creation (checkbox) is disabled

izpack-dist/src/main/izpack/shortcutSpec.xml
Just a easily fixable warning in console output on macOS.
=> IZPACK-1604: fix warning at shortcut creation

izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java
Based on the post of Andrew Hall on the issue's JIRA page.
Instead of doing a first try to get the 'src' or 'dir' attribute without variable substitution, we retrieve the substituted value (only when it was handled or needed) and then add the baseDir absolute path.
=> IZPACK-1552: fix wrong property substitution for 'dir' and 'src' attributes

izpack-compiler/src/main/resources/schema/5.0/izpack-userinput-5.0.xsd
The xsd has been updated to validate the attribute "omitOnAuto".
It might have been forgotten in:
https://izpack.atlassian.net/browse/IZPACK-1138
=> Update user-input xsd to validate omitOnAuto (IZPACK-1138)

izpack-core/src/main/java/com/izforge/izpack/core/resource/DefaultLocales.java
This PR fixes the problem with the wrong language in the language selection dialog under Java 9+. The flag was correct, but the language was always 'English'.
=> IZPACK-1613: Fixed issue with wrong locale under Java 9.

izpack-installer/src/main/java/com/izforge/izpack/installer/gui/InstallerFrame.java
Use reflection to set the installer frame's WM_CLASS to its title.
This improves the appearance of the installer in application switchers on Linux desktops.
=> Set the installer frame's WM_CLASS to its title.

izpack-panel/src/main/java/com/izforge/izpack/panels/jdkpath/JDKPathPanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/jdkpath/JDKPathPanelHelper.java, izpack-panel/src/main/java/com/izforge/izpack/panels/path/PathInputPanel.java
IZPACK-1648: Check for existance of bin/javac if no bib/tools.jar is found. This will work for JDK9+.
=> IZPACK-1648: Allow to select JDK9+ in JDKPathPanel

.gitignore, izpack-core/src/main/java/com/izforge/izpack/core/resource/ResourceManager.java
Caused by: com.izforge.izpack.api.exception.ContainerException:
com.izforge.izpack.api.exception.ResourceNotFoundException: Cannot find
named resource: 'info'
Signed-off-by: Francis ANDRE <francis.andre.kampbell@orange.com>
=> Fix for the IzPack exception: ResourceNotFoundException: Cannot find named resource: 'info'

izpack-panel/src/main/java/com/izforge/izpack/panels/jdkpath/JDKPathConsolePanel.java
the variable jdkPath will now be parsed when
present in a properties file and will be added
to the installation data.
=> fix bug IZPACK-1578

izpack-wrapper/src/main/resources/utils/wrappers/izpack2app/izpack2app.py
Traceback (most recent call last):
File "izpack2app\izpack2app.py", line 53, in <module>
main()
File "izpack2app\izpack2app.py", line 43, in main
plist_content = reduce(reducer, plist.readlines(), '').replace('__JAR__', jar_name)
NameError: name 'reduce' is not defined
=> Fix for problem name 'reduce' is not defined

izpack-ant/src/main/java/com/izforge/izpack/ant/IzPackTask.java, izpack-ant/src/main/java/com/izforge/izpack/ant/Property.java
Fixes nested `<property>` elements being ignored by implementing a custom property that supports the `value` and `refid` as the original ANT property.
=> IZPACK-1663 created custom property in order to be independent

izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/UserInputConsolePanel.java
IZPACK-1640 - fix panel processors not being visited in console mode
=> IZPACK-1640 - fix panel processors not being visited in console mode

pom.xml
This fixes the following CVE reports:
commons-compress-1.12.jar (pkg:maven/org.apache.commons/commons-compress@1.12, cpe:2.3:a:apache:commons-compress:1.12:*:*:*:*:*:*:*, cpe:2.3:a:apache:commons_compress:1.12:*:*:*:*:*:*:*) : CVE-2018-11771, CVE-2018-1324
pdfbox-1.8.10.jar (pkg:maven/org.apache.pdfbox/pdfbox@1.8.10, cpe:2.3:a:apache:pdfbox:1.8.10:*:*:*:*:*:*:*) : CVE-2016-2175, CVE-2018-11797, CVE-2018-8036
=> IZPACK-1667 - Updating Commons Compress and Pdfbox

izpack-installer/src/main/java/com/izforge/izpack/util/os/WinSetupFileQueue.java
https://izpack.atlassian.net/browse/IZPACK-1656
Use correct parameter to prefent error wile file queue operstion: "De parameter is onjuist" or  "The parameter is incorrect"
Enqueueing moving C:\Program Files\CENSORED\CENSORED\__FQ__9356852580364207950.tmp to C:\Program Files\CENSORED\CENSORED\CENSORED.exe (0x201)
java.io.IOException: File queue operation failed due to Failed to enqueue moving C:\Program Files\CENSORED\CENSORED\__FQ__9356852580364207950.tmp to C:\Program Files\CENSORED\CENSORED\CENSORED.exe due to SetupQueueCopy returned with code 87: De parameter is onjuist.
at com.izforge.izpack.util.os.FileQueue.execute(FileQueue.java:89)
at com.izforge.izpack.installer.unpacker.UnpackerBase.postUnpack(UnpackerBase.java:754)
at …
=> Issue: IZPACK-1656 fix file queue parameter

izpack-installer/src/main/java/com/izforge/izpack/installer/unpacker/CompressedFileUnpacker.java
Checks the read size against the size either defined on the current and back referenced file size if available. As there are cases where the only the back reference contains the correct size,
=> IZPACK-1645 enhanced size check for reading before unpack

izpack-event/src/main/java/com/izforge/izpack/event/RegistryInstallerListener.java
If found an issue in the tests running with administator rights under Windows that was caused by my previous fix for IZPACK-1686.
=> IZPACK-1686: Fix NPE if the 'EstimatedSize' is not in installData.

izpack-core/src/main/java/com/izforge/izpack/core/data/AutomatedOverrides.java, izpack-installer/src/main/java/com/izforge/izpack/installer/automation/AutomatedPanels.java, izpack-installer/src/main/java/com/izforge/izpack/installer/bootstrap/Installer.java
This change allow to use `-auto` argument without providing any `-defaults-file`. 
I'm a new user of IzPack, and the whole purpose of an installer is to build a single file for the package. But I could not run the `-auto` installation without providing an aditionnal `-defaults-file` file. I could not understand this behavior and was really frustrated to discover this limitation after spending some time to learn the framework and build the whole installer, so here's a pull request that I have tested against my installer project.
IzPack is a nice piece of software tough, I wrote again a Swing JPanel 10 years after good old times, thanks for maintaining it.
=> Allow -auto argument without -defaults-file

izpack-installer/src/main/java/com/izforge/izpack/installer/unpacker/LooseFileUnpacker.java
If provided, search for loose files in folder specified by 'looseFilesDir' property.
=> [IZPACK-1702] Optional parameter to be used while searching loose files

.github/workflows/maven.yml, .github/workflows/settings.xml
Deploys a SNAPSHOT to [Sonatype](https://oss.sonatype.org/content/repositories/snapshots/org/codehaus/izpack/) after each successful build of the `master` branch.
=> Enable snapshot deployments

izpack-core/src/main/java/com/izforge/izpack/core/substitutor/VariableSubstitutorInputStream.java, izpack-core/src/test/java/com/izforge/izpack/core/substitutor/VariableSubstitutorInputStreamTest.java
In turn fixes following bug as well:
[IZPACK-1478] Offer streams API for variable substitution on the fly
[IZPACK-1617] XML files in UTF-8 were broken by inserting variables if they "parsable". Non-latin chars become spoiled.
[IZPACK-1676] Creating Windows start menu shortcuts fails if installation directory contains non-ASCII characters
[IZPACK-1478]: https://izpack.atlassian.net/browse/IZPACK-1478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IZPACK-1617]: https://izpack.atlassian.net/browse/IZPACK-1617?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IZPACK-1676]: https://izpack.atlassian.net/browse/IZPACK-1676?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1 …
=> [IZPACK-1642] The substitution does not work correctly on non-Latin encoding (VariableSubstitutorInputStream)

izpack-panel/src/main/java/com/izforge/izpack/panels/process/ProcessPanelWorker.java
This should resolve the following problem on linux (ubuntu) when doing a re-install.
`[ Starting processing ]
Starting process Remove Previously Installed Service (1/1)
I/O error:
java.io.IOException: Cannot run program ""/usr/local/app/uninstall-service.sh"": error=2, No such file or directory`
Note the double quotes in the exception, caused by a recent PR:
https://github.com/izpack/izpack/pull/749
=> [IZPACK-508] Only append quotes when required

izpack-tools/src/main/java/com/izforge/izpack/util/FileUtil.java, izpack-tools/src/test/java/com/izforge/izpack/util/FileUtilTest.java
**Root Cause**: ClassLoader.getResources() method returns URL without escaping special characters (e.g. space).
**Fix**: Use round about way to form URI such that the special characters are escaped, please refer to the code
=> [IZPACK-1675] IzPack Ant Task fails if a file system path contains whitespace (or any other char not allowed in a URL)

izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java
**Root Cause**: Exception message did not capture the details.
**Fix**: Capturing details in exception message
=> [IZPACK-584] IzPack compiler fails without giving proper information

izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java, izpack-core/src/main/java/com/izforge/izpack/core/rules/process/RefCondition.java
**Root Cause**: At compile time the condition resolver was called before all the conditions are generated (especially, the pack selection conditions). At runtime, installData was null for referenced conditions and caused null pointer exception.
**Fix**: Moved condition resolver after packs are added. Added installData for referenced conditions if it is not set.
=> [IZPACK-1605] Or-Condition adds conditions to id maps and leads to duplicate key exception

izpack-api/src/main/java/com/izforge/izpack/api/installer/ISummarisable.java, izpack-installer/src/main/java/com/izforge/izpack/installer/gui/IzPanel.java, izpack-installer/src/main/java/com/izforge/izpack/installer/util/SummaryProcessor.java
Extended ISummarisable intrface in order to remove the down cast from
IzPanel in order to get the visited status. This allows for other panel
implementations and more easy testing.
Signed-off-by: Patrick Reinhart <patrick@reini.net>
=> IZPACK-1721 Removes IzPack panel dependency

izpack-api/src/main/java/com/izforge/izpack/api/GuiId.java, izpack-installer/src/main/java/com/izforge/izpack/installer/console/AbstractTextConsolePanel.java, izpack-installer/src/main/java/com/izforge/izpack/installer/util/PanelHelper.java, izpack-panel/src/main/java/com/izforge/izpack/panels/info/InfoConsolePanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/info/InfoPanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/xinfo/XInfoPanel.java
[IZPACK-1727] Variable substitution happens for InfoPanel in console mode
[IZPACK-1728] XInfoPanel title is aligned right instead of left
[IZPACK-1729] Support InfoPanel.font variable similar to XInfoPanel.font
[IZPACK-1727]: https://izpack.atlassian.net/browse/IZPACK-1727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IZPACK-1728]: https://izpack.atlassian.net/browse/IZPACK-1728?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IZPACK-1729]: https://izpack.atlassian.net/browse/IZPACK-1729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IZPACK-1727, IZPACK-1728 and IZPACK-1729

izpack-compiler/pom.xml, izpack-dist/pom.xml
- removed no longer existing schemal resource folder
- use plugins managed version
- prepare for maven resource plugin update (needs [plugin fix](https://issues.apache.org/jira/browse/MRESOURCES-301))
=> Cleanup version definition & adds filter exclusion

izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java, izpack-compiler/src/test/java/com/izforge/izpack/compiler/CompilerConfigSamplesTest.java, izpack-compiler/src/test/resources/samples/refpackincludes/izpack-module.xml, izpack-compiler/src/test/resources/samples/refpackset/izpack.xml
Using refPackSet causes trouble when resolving packDir if refFile is absolute. In this case two absolute paths are combined, leading to "Invalid file" exception.
With this pull request absolute and relative paths are handled.
Testcase and test installer files prove the change. Running the testcase on current master will lead to:
`com.izforge.izpack.api.exception.CompilerException: Invalid file: D:\projects\izpack\izpack-compiler\target\test-classes\samples\refpackset\D:\projects\izpack\izpack-compiler\target\test-classes\samples\refpackset\..\refpackincludes\izpack-module.xml while processing refpackset refpackset
at com.izforge.izpack.compiler.CompilerConfig.addPacksSingle(CompilerConfig.java:1018)
at com.izforge.izpack.compiler.CompilerConfig.addPacks(CompilerConfig.java:771)
at …
=> IZPACK-1747 Enable refPackSet to resolving packDir if refFile is absolute

izpack-panel/src/main/java/com/izforge/izpack/panels/shortcut/ShortcutPanel.java
- Initialize program group GUI field until panelActivate() in oder to pick up potential new variables introduced after construction to be properly resolved.
- Using isEmpty() instead of "".equals(x)
- Fixed typo
=> IZPACK-1748 Delay programGroup to panelActivate()

izpack-compiler/src/main/java/com/izforge/izpack/compiler/container/provider/JarOutputStreamProvider.java, izpack-compiler/src/main/java/com/izforge/izpack/compiler/packager/impl/PackagerBase.java
- Properly closing the JarInputStream after installer creation
- Using diamond operators
- Use of NIO instead old File
=> [IZPACK-1751] Fixes 'inconsistent archive'

pom.xml
Bumps org.apache.pdfbox:pdfbox from 3.0.1 to 3.0.2.
=> Bump org.apache.pdfbox:pdfbox from 3.0.1 to 3.0.2

izpack-api/src/main/java/com/izforge/izpack/api/data/ScriptParserConstant.java, izpack-installer/src/main/java/com/izforge/izpack/installer/container/provider/AbstractInstallDataProvider.java
Added a new installer variable `CANONICAL_HOST_NAME` that contains the fully qualified host name (FQDN) from `InetAddress.getLocalHost().getCanonicalHostName()`
=> [IZPACK-1768] Adds canonical host name variable

izpack-compiler/src/main/java/com/izforge/izpack/compiler/data/PropertyManager.java, izpack-compiler/src/main/resources/schema/5.0/izpack-installation-5.0.xsd
- Made property attribute 'name' optional as it is not used when specifying the 'file' attribute
- Enhanced property manager to differetiate between relative and absolute file names
=> IZPACK-1776 Re-enable file based property values

izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java
Fixes file path handling to use base directory for referred pack file and its parent directory for reading the files.
=> IZPACK-1781 Fix import handling for packref

izpack-dist/src/main/resources/bin/compile, izpack-panel/src/main/java/com/izforge/izpack/panels/jdkpath/JDKPathPanel.java, izpack-panel/src/main/java/com/izforge/izpack/panels/jdkpath/JDKPathPanelHelper.java, src/doc-reST/panels.txt, src/doc-reST/user-input.txt
Drops usage of `tools.jar` to determine the presence of a Java JDK Installation.
=> IZPACK-1782 Remove references to tools.jar

izpack-compiler/src/main/java/com/izforge/izpack/compiler/data/PropertyManager.java
Expand the property file name value prior of trying to load the properties content.
=> [IZPACK-1783] Expand property file name variables

izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java
Always use the current base directory for reading the pack data defined in a referred revpack file when not specified using an absolute path.
=> [IZPACK-1781] Always use base directory for refpack

build, pom.xml
Provides a fix for IZPACK-1786 (thanks to @paul-hammant to still support JDK 8)
=> Bump org.picocontainer:picocontainer from 2.15 to 2.15.2

izpack-maven-plugin/src/main/java/org/izpack/mojo/IzPackNewMojo.java
Logs missing properties as warning instead of throwing a NPE
=> [IZPACK-1800] Fix NPE if property value missing
